export const SERVICE_URL =
  "https://servicios3.abc.gob.ar/valoracion.docente/api/apd.oferta.encabezado/select";
export const FACET_PARAMS =
  "rows=0&facet=true&facet.limit=-1&facet.mincount=1&json.nl=map&facet.field=cargo&facet.field=estado&facet.field=descnivelmodalidad&facet.field=descdistrito&q=*:*&wt=json";
export const SCHOOL_SERVICE_URL =
  "https://servicios3.abc.gob.ar/oferta.educativa/api/establecimiento/collapsed/select";
// ?q=*%3A*&fq=CLAVEESTAB%3A0032JI0908&wt=json
export const POSTULANTES_SERVICE_URL =
  "https://servicios3.abc.gob.ar/valoracion.docente/api/apd.oferta.postulante/select";
// ?fq=idoferta%3A3915102&q=idoferta%3A3915102&rows=10&sort=estadopostulacion%20asc%2C%20orden%20asc%2C%20puntaje%20desc&wt=json

export const TURNOS = {
  M: "Mañana",
  T: "Tarde",
  V: "Vespertino",
  A: "Alternado",
  MT: "Mañana y Tarde",
  N: "Noche",
} as const;

export const JORNADAS = {
  JS: "Jornada Simple",
  JC: "Jornada Completa",
} as const;

export const REVISTA = {
  S: "Suplencia",
  P: "Provisionalidad",
} as const;

export const CARGO_KEYS = [
  " derecho económico y del trabajo (cta)",
  " fines educación artística: danza (wdz)",
  " fines educación artística: música  (wmc)",
  " fines educación artística: plástica   (wpv)",
  " fines educación artística: teatro (wtt)",
  " fines educación física  (wfc)",
  "4ta proyecto, diseño e instalaciones de energías renovables (pd4)",
  "5ta proyecto, diseño e instalaciones de energías renovables (pd5)",
  "abordaje de la interpretacion (ydi)",
  "actuacion (a.c)",
  "actuacion (ctu)",
  "actuación y procedimientos constructivos en teatro (poc)",
  "administracion (a.d)",
  "administracion de capacidades-gestion econimico comercial (cag) (cag)",
  "administración y gestión de los recursos humanos  (arh)",
  "agroalimentos (aga)",
  "alimentos (a.l)",
  "ambiente, desarrollo y sociedad (ads)",
  "analisis del lenguaje teatral (yea)",
  "analisis y produccion en musica (yem)",
  "antropologia (a.n)",
  "antropologia y cultura (an2)",
  "análisis coreográfico (cor)",
  "análisis de modelos circuitales (moc)",
  "análisis de producción en música (pem)",
  "análisis del lenguaje teatral (tea)",
  "análisis matemático (am)",
  "aplicaciones de electrónica analógica (aea)",
  "aplicaciones de electrónica digital (aed)",
  "area administracion (/2a)",
  "area administracion cens - adultos (+2a)",
  "area antropologia cens - adultos (+2g)",
  "area ciencias biologicas cens - adultos (+3a)",
  "area ciencias de la educacion cens - adultos (+2o)",
  "area comunicacion cens - adultos (+3e)",
  "area contabilidad cens - adultos (+2r)",
  "area cs.politicas y juridicas cens - adultos (+2u)",
  "area economia cens - adultos (+3g)",
  "area filosofia cens - adultos (+3p)",
  "area fisica cens - adultos (+5x)",
  "area historia cens - adultos (+3w)",
  "area informatica cens - adultos (+3z)",
  "area ingles cens - adultos (+4f)",
  "area ingles de la educacion general basica-egb (/ai)",
  "area lengua y literatura cens - adultos (+4b)",
  "area matematica cens - adultos (+4i)",
  "area medicina cens - adultos (+4o)",
  "area psicologia cens - adultos (+4s)",
  "area quimica cens - adultos (+5y)",
  "area sociologia cens - adultos (+4w)",
  "area tecnologia cens - adultos (+3d)",
  "areas de centro de produccion total (cpt)",
  "arte (leng. compl. de la danza): artes visuales (cd3)",
  "arte (leng. compl. de la danza): música (cd2)",
  "arte (leng. compl. de la danza): teatro (cd1)",
  "arte (leng. compl. de la lit.): artes visuales (cl2)",
  "arte (leng. compl. de la lit.): danza (cl3)",
  "arte (leng. compl. de la lit.): música (cl4)",
  "arte (leng. compl. de la literatura): teatro (cl1)",
  "arte (leng. compl. de la música): artes visuales (cm2)",
  "arte (leng. compl. de la música): danza (cm3)",
  "arte (leng. compl. de la música): teatro (cm1)",
  "arte (leng. compl. de las artes visuales): danza (ca3)",
  "arte (leng. compl. de las artes visuales): música (ca2)",
  "arte (leng. compl. de las artes visuales): teatro (ca1)",
  "arte (leng. compl. del  teatro): danza (ct3)",
  "arte (leng. compl. del teatro): artes visuales (ct2)",
  "arte (leng. compl. del teatro): música (ct1)",
  "arte (rte)",
  "arte digital y diseño web (adw)",
  "asistente educacional (*ae)",
  "asistente social (*as)",
  "auditoria y control de gestión (aud)",
  "ayudante del area musica en danza clasica (m7a)",
  "ayudante del area musica-canto (a3k)",
  "ayudante del area musica-iniciacion (a3a)",
  "ayudante del area musica-practica de conjunto (a3b)",
  "bases de datos (bdd)",
  "bibliotecario (/be)",
  "bibliotecario (/bi)",
  "bibliotecario (/bp)",
  "bibliotecario (bla)",
  "bibliotecario de cens (/ba)",
  "bibliotecario de cie (bie)",
  "bibliotecario institutos terciarios artistica (bli)",
  "bibliotecario nivel inicial (/bj)",
  "biologia (b.g)",
  "biologia (blg)",
  "biologia y su enseñanza (b.p)",
  "biología y ambiente - biología y salud (c3a)",
  "biología, genética y sociedad (bgs)",
  "c.e.: administración de capacidades - gestión económico comercial (jag)",
  "c.e.: bases de datos y proyecto de software libre (jbp)",
  "c.e.: bibliotecario en contexto de encierro (jbi)",
  "c.e.: biología y ambiente/ biología y salud (j3a)",
  "c.e.: ciencias sociales 1 y 2 (jvw)",
  "c.e.: ciudadanía, sociedad y cultura - relaciones laborales y orientación profesional (j2u)",
  "c.e.: comunicación y cultura (jcc)",
  "c.e.: derecho ambiental y políticas ambientales (jda)",
  "c.e.: derecho económico y del trabajo (jet)",
  "c.e.: derechos humanos (jdh)",
  "c.e.: desarrollo sustentable 1 y 2 (jal)",
  "c.e.: economía y economía popular, social y solidaria (jee)",
  "c.e.: educación artística 1 y 2  plastica (jpv)",
  "c.e.: educación artística 1 y 2 teatro (jat)",
  "c.e.: educación física 1 y 2 (jfc)",
  "c.e.: filosofía (jff)",
  "c.e.: física: fenómenos naturales y procesos productivos (j5x)",
  "c.e.: gestión del diseño de emprendimientos/administración pública (j2a)",
  "c.e.: historia-geografia (jhg)",
  "c.e.: ingles (jin)",
  "c.e.: legislación y práctica impositiva - herramientas legales para emprendimientos (jlh)",
  "c.e.: lengua adicional ingles (j4f)",
  "c.e.: maestro bibliotecario (jmb)",
  "c.e.: maestro de ciclo (jcl)",
  "c.e.: matematica (jma)",
  "c.e.: matemática 1 y 2 (j4i)",
  "c.e.: metodología de la investigación (jmm)",
  "c.e.: preceptor (jpk)",
  "c.e.: primera disciplina/ lenguaje de la orientación 1 y 2 teatro (jlt)",
  "c.e.: probl. social contemporánea (jhp)",
  "c.e.: problemática social argentina (jpp)",
  "c.e.: proyecto de producción teatro -proyecto producción (jjt)",
  "c.e.: prácticas del lenguaje 1 y 2 (j4b)",
  "c.e.: quimica (jqu)",
  "c.e.: salud: género y trabajo (jss)",
  "c.e.: sistemas contables/gestión contable de emprendimientos (j2r)",
  "c.e.: sociologia (jso)",
  "c.e.: sociología 1 y 2 (j4w)",
  "c.e.: tecnología y prácticas digitales 1 y 2 (j3z)",
  "canto coral (ycn)",
  "canto popular (ycr)",
  "capital humano y relaciones laborales (chr)",
  "centrales eléctricas (cen)",
  "cereales (cer)",
  "ciencias de la educacion (c.e)",
  "ciencias de la tierra (cdt)",
  "ciencias naturales (cnt)",
  "ciencias politicas (c.p)",
  "ciencias sociales (csc)",
  "ciencias sociales 1 -2  (cvw)",
  "ciudadania, sociedad y cultura-relaciones laborales y orientacion profesional (c2u) (c2u)",
  "cobertura de asignaturas formación profesional (fpg)",
  "combustión de los motores endotérmicos (moe)",
  "comportamiento de las estructuras (cde)",
  "comunicacion social (c.s)",
  "comunicación y cultura 1-2 (ccc) (ccc)",
  "comunicación y culturas del consumo (cyc)",
  "comunicación y transf. socioculturales siglo xxi (cyt)",
  "comunicación, cultura y sociedad (ccs)",
  "conocimiento de los materiales (m. mayor de obras) (cmm)",
  "conocimiento de los materiales (téc. automotores) (cma)",
  "conocimiento de los materiales (téc. electromec.) (cme)",
  "construccion de ciudadania (ccd)",
  "contables (c.b)",
  "controles y automatismo  (4°, 5° y 6° año) (cya)",
  "coordinador institucional (coi)",
  "coordinador institucional de trayectorias educativas (cit)",
  "costos (cos)",
  "danza (adz)",
  "danza clasica i, ii, iii y iv (ycl)",
  "danza folklorica y popular i, ii, iii, iv y v (yfp)",
  "danzas expresion corporal (*7c)",
  "danzas tradicionales argentinas (*7b)",
  "deportes abiertos (d.a)",
  "derecho (der)",
  "derecho (drc)",
  "derecho administrativo (d.d)",
  "derecho ambiental y politicas ambientales (cdp) (cdp)",
  "derecho civil (d.c)",
  "derecho comercial (d.m)",
  "derecho del trabajo y seguridad social (d.t)",
  "derecho penal (d.p)",
  "derechos del trabajo (det)",
  "derechos humano 1-2 (cdh) (cdh)",
  "derechos humanos y ciudadanía  (dhu)",
  "desarrollo de aplicaciones web dinámicas (dwd)",
  "desarrollo de aplicaciones web estáticas (dwe)",
  "desarrollo regional (crd) (crd)",
  "desarrollo sustentable 1 - 2 (cal)",
  "destinos turisticos  (tdt)",
  "dibujo tecnológico (maestro mayor de obras) (dtm)",
  "dibujo tecnológico (tecnico automotores) (dta)",
  "dibujo tecnológico (tecnico electromecanica) (dte)",
  "didactica de la biologia (dbi)",
  "didactica de las ciencias naturales (dcn)",
  "didactica de las ciencias sociales - historia (dch)",
  "didactica y curriculum (dyc)",
  "dificil cobertura (dca)",
  "dinamica de grupos (pc2)",
  "dirección de la ejecución de instalaciones (dej)",
  "director (xxd)",
  "director de escuela de verano (dev)",
  "diseño asistido y simulación electrónica (das)",
  "diseño de emprendimientos turisticos (cjf)",
  "diseño y gestion de proyectos turisticos sociocomunitarios (dgp)",
  "diseño y gestión de proyectos (dis)",
  "diseño y procesamiento mecánico (prm)",
  "docente coordinador/a de trayectorias - resol.1873/22 (ps6)",
  "docente integrador de circulos y trayectorias (d8d)",
  "documentación técnica (dot)",
  "economia y economia  popular, social y solidaria (cec)",
  "economía (eno)",
  "economía política (epo)",
  "educacion (*4a)",
  "educacion fisica (e.f)",
  "educacion fisica (efc)",
  "educacion fisica y su enseñanza (e.d)",
  "educación artística 1 - 2: música  (cmc)",
  "educación artística 1 -2 : danza  (cdz)",
  "educación artística 1 -2: plástica (cpv)",
  "educación artística 1 -2: teatro (ctt)",
  "educación física 1- 2 (cfc)",
  "educación física y comunidad (efu)",
  "educación física y corporeidad (fco)",
  "educación física y cultura (efi)",
  "eficiencia energética y uso racional de la energía (eer)",
  "ejercico profesional de la construcción (epc)",
  "electrotecnia (nia)",
  "electrotecnia del automotor (eau)",
  "electrotecnia y electronica (t.e.i.e.) (-6k)",
  "electrónica (ect)",
  "electrónica aplicada (ela)",
  "electrónica industrial (ein)",
  "electrónica y autotrónica (nic)",
  "elementos de micro y macro economía (emm)",
  "ematp tecnología de la leche (etl)",
  "emprendimientos productivos y desarrollo local (edl)",
  "enc. de medios de apoyo tec-pedag. en c.sociales (ecs)",
  "enc.medios apoyo tecnico-pedag.especialidad taller (/pa)",
  "encarg. medios apoyo tec. pedag. area informatica (pli)",
  "encargado medios apoyo tec-ped. cs fisicas (eff)",
  "encargado medios apoyo tec-ped.biologia (ebb)",
  "encargado medios apoyo tec-ped.comunic. arte y dis (ead)",
  "encargado medios apoyo tec-ped.construc.civiles (eco)",
  "encargado medios apoyo tec-ped.econ.y ges.organiza (elc)",
  "encargado medios apoyo tec-ped.electronica (eel)",
  "encargado medios apoyo tec-ped.inf/comp/e inf.apl. (eli)",
  "encargado medios apoyo tec-ped.med/equip/ins.elec. (eld)",
  "encargado medios apoyo tec-ped.quimica (eqq)",
  "encargadomedios apoyo tec-ped.biologia (ebb)",
  "escenoplastica (ysc)",
  "escuela de verano contexto de encierro (cev)",
  "escuela de verano educación física (vef)",
  "escuela de verano guardavida (vgu)",
  "espacio complementario ( escultura ) (yce)",
  "espacio complementario ( grabado) (ycg)",
  "espacio de la especialidad (grabado ) (yeg)",
  "espacio de la especialidad (pintura ) (ypi)",
  "espacio de profundizacion del aprendizaje (epa)",
  "espacios turísticos de la argentina (eta)",
  "estructuras (esr)",
  "estudios interculturales en inglés (est)",
  "filosofia (*6a)",
  "filosofia (f.i)",
  "filosofia (fia)",
  "filosofia 1-2 (cff) (cff)",
  "filosofía (fia)",
  "filosofía e historia de la ciencia y la tecnología (fct)",
  "fines administración pública, de capacidades y relaciones laborales 2do año (waa)",
  "fines biología (wcb)",
  "fines ciudadanía, sociedad, cultura y relaciones laborales 2do año (wcr)",
  "fines comunicación y cultura 3er año (wcc)",
  "fines comunicación y medios (wcm)",
  "fines contabilidad (wco)",
  "fines derecho (wdd)",
  "fines derechos humanos 2do año (wdh)",
  "fines educación artística: literatura y escritura  (wle)",
  "fines educación artística: música  (wmc)",
  "fines educación artística: plástica   (wpv)",
  "fines educación física  (wfc)",
  "fines filosofía 3er año (wfp)",
  "fines fisica (wff)",
  "fines fundamentos de economía y perspectiva popular, social y solidaria 3er año (weg)",
  "fines historia y geografia (whg)",
  "fines informática (wif)",
  "fines ingles (win)",
  "fines legislación impositiva y herramientas para emprendimientos 3er año (wru)",
  "fines lengua y literatura (wll)",
  "fines matemática (wmt)",
  "fines metodología de la investigación (wmi)",
  "fines planificacion y gestion de emprendimientos (esp.2º) (wpg)",
  "fines practica contable laboral e impositiva (esp.3º) (wpc)",
  "fines problemática social argentina 3er año (wsp)",
  "fines problemática social contemporanea (wps)",
  "fines psicología (wpa)",
  "fines quimica (wqq)",
  "fines sociología (wss)",
  "fisica y su enseñanza (f.t)",
  "fisica: fenomenos naturales y procesos productivos (c5x) (c5x)",
  "fisico - quimica (fqa)",
  "fonoaudiologia (f.n)",
  "fonoaudiologo (/fo)",
  "forrajes (frj)",
  "fortalecimiento de trayectorias educativas (inicial) (mif)",
  "fortalecimiento de trayectorias educativas (primaria) (mgf) [prog. res. 417/21- 3206/21- 446/22 ] (mgf)",
  "fotografia (yot)",
  "francés (fra)",
  "fundamentos de la química (fdq)",
  "fundamentos de los modelos circuitales (fmc)",
  "fundamentos y modelos de mecanica clasica (fmm)",
  "física (fis)",
  "física clásica y moderna (fcm)",
  "ganaderia (gnd)",
  "ganaderia de carne (gca)",
  "ganadería de leche (gdl)",
  "genetica y evolucion (g.e)",
  "geografia (g.f)",
  "geografia (ggf)",
  "geografia de genero (gge)",
  "geografia y su enseñanza (g.p)",
  "gestión comercial (gco)",
  "gestión de la producción (ges)",
  "gestión de las energías renovables (ger)",
  "gestión de proyectos (gdp)",
  "gestión de proyectos (gpr)",
  "gestión del diseño de emprendimientos - administración pública (c2a)",
  "gestión financiera bancaria y seguros (fin)",
  "gestión organizacional (gor)",
  "granja 1º y 2º año (gra)",
  "gráfica editorial (gre)",
  "guardavidas (gu)",
  "guión (5° año) (gui)",
  "historia (h.i)",
  "historia (htr)",
  "historia contemporanea (h.c)",
  "huerta (hue)",
  "imagen y nuevos medios (inm)",
  "imagen y nuevos medios (ynm)",
  "imagen y procedimientos constructivos (lep)",
  "imagen y procedimientos constructivos (yip)",
  "improvisación y composición coreográfica (imp)",
  "informatica (i.f)",
  "ingles (i.n)",
  "ingles (igs)",
  "inglés específico (ing)",
  "iniciacion a la danza folklorica y popular (ydf)",
  "instalaciones de baja tensión y media tensión (ibt)",
  "instalaciones eléctricas (ie)",
  "instalaciones industriales (iim)",
  "instalaciones industriales (ind)",
  "instalaciones sanitarias y de gas (isi)",
  "instalaciones y aplicaciones de la energía (ape)",
  "instalaciones y maquinas eléctricas (imo)",
  "instalación, mantenimiento y reparación de redes informáticas (iri)",
  "instalación, mantenimiento y reparación de sistemas computacionales (imc)",
  "instructor/a de formación profesional - resol.1873/22 (ps5)",
  "instrumental de medición (imu)",
  "instrumento  (yns)",
  "instrumento (piano o guitarra) (yii)",
  "instrumento complementario (ync)",
  "instrumento principal (ynp)",
  "intensificación agropecuaria (ia)",
  "interpretación de anteproyectos (ian)",
  "introduccion a los multimedios (iam)",
  "introduccion al portugues (ipo)",
  "introducción a la biología celular (ibc)",
  "introducción a la comunicación (iac)",
  "introducción a la electricidad y mediciones (iem)",
  "introducción a la física (iaf)",
  "introducción a la programación orientada a objetos (ioo)",
  "introducción a la química (iaq)",
  "introducción a las organizaciones (ior)",
  "introducción al turismo - prestadores turísticos (c5a)",
  "introducción al turismo y oferta turística (itt)",
  "investigación del medio 1° y 2° año (ime)",
  "investigación operativa (ope)",
  "italiano (ita)",
  "jornada escolar de 25 horas- maestro de apoyo - [prog. res. 2502/22] (ma5)",
  "jornada escolar de 25 horas- maestro de grado - [prog. res. 2502/22]  (mg5)",
  "kinesiologo (/ki)",
  "lab. de op. unit. y tecnología de los materiales (lot)",
  "laboratorio de análisis microbiológicos (lam)",
  "laboratorio de aplicaciones (lap)",
  "laboratorio de diseño de bases de datos (ldb)",
  "laboratorio de diseño web (ldw)",
  "laboratorio de ensayo de motores (ens)",
  "laboratorio de ensayos físicos (lef)",
  "laboratorio de ensayos industriaes (lei)",
  "laboratorio de hardware (lhw)",
  "laboratorio de mediciones electricas (lme)",
  "laboratorio de metrología y control de calidad (lcc)",
  "laboratorio de procesos industriales (lpi)",
  "laboratorio de procesos industriales (pri)",
  "laboratorio de programación (lpr)",
  "laboratorio de quimica organica biologica y micro (qui)",
  "laboratorio de química (lqi)",
  "laboratorio de química orgánica (qor)",
  "laboratorio de química orgánica, biológica y microbiológica (alimentos) (qua)",
  "laboratorio de redes informáticas (lri)",
  "laboratorio de sistemas operativos (lso)",
  "laboratorio de técnicas analíticas (tec)",
  "legislacion y practica monetaria-herramientas legales para emprendimientos (clh) (clh)",
  "lengua (l.n)",
  "lengua adicional 1 - 2: inglés  (c4f)",
  "lengua y su enseñanza (l.p)",
  "lenguaje complementario (artes visuales) (yca)",
  "lenguaje complementario (danza) (ylz)",
  "lenguaje complementario (musica) (ycm)",
  "lenguaje complementario (teatro) (ylt)",
  "lenguaje de la danza (led)",
  "lenguaje musical  (yen)",
  "lenguaje musical (len)",
  "lenguaje visual i y ii (yvl)",
  "lenguajes artísticos/ música (ltm)",
  "lenguajes artísticos/ plástica (ltp)",
  "lenguajes artísticos/ teatro y diseño escenográfico (ltt)",
  "lenguajes electrónicos (lee)",
  "lenguajes musicales contemporaneos (ymc)",
  "lenguajes tecnológicos (lt1)",
  "lenguajes tecnológicos (lt2)",
  "lenguajes tecnológicos (lte)",
  "lenguajes tecnológicos (lts)",
  "linguistica (l.g)",
  "literatura (l.t)",
  "literatura (lit)",
  "logistica (l.o)",
  "líneas de transmisión (ltr)",
  "ma-agricultura (agr)",
  "ma-avicultura (avi)",
  "ma-bovinos de carne (boc)",
  "ma-bovinos de leche (bol)",
  "ma-cunicultura (cun)",
  "ma-huerta (hor)",
  "ma-mecánica agrícola (meg)",
  "ma-máquinas, equipos, herramientas e inst. rurales (mir)",
  "ma-ovinos (ovi)",
  "ma-planta de elaboración de forrajes (efo)",
  "ma-porcinos (pos)",
  "ma-sala de elaboración de productos cárnicos (eca)",
  "ma-sala de elaboración de productos lácteos (epl)",
  "ma-sala de frutas y hortlizas (sfh)",
  "ma-taller rural (trm)",
  "ma-vivero (pvi)",
  "maest.auxiliar taller armado (*ra)",
  "maest.auxiliar taller carpinteria (*ca)",
  "maest.auxiliar taller confeccion (*cf)",
  "maest.auxiliar taller construcciones (*cn)",
  "maest.auxiliar taller mecanica (*tm)",
  "maest.auxiliar taller peluqueria (*pl)",
  "maest.auxiliar taller servicios (*ts)",
  "maestra bibliotecaria rama adultos (/mb)",
  "maestra de infantes (/mi)",
  "maestra de jardin maternal (/jm)",
  "maestra de pre-taller de costura (/tc)",
  "maestra hospitalaria (/dh)",
  "maestra iniciacion literaria escuelas de estetica (mil)",
  "maestro alteraciones en el desarrollo del lenguaje (/al)",
  "maestro ciegos y disminuidos visuales (/dc)",
  "maestro de apoyo (ma)",
  "maestro de apoyo para escuelas laborales (/ab)",
  "maestro de armado (/ra)",
  "maestro de articulacion (/ar)",
  "maestro de ciclo (/mc)",
  "maestro de danza primaria (mdp)",
  "maestro de danza primaria de especial (mde)",
  "maestro de discapacitados motores (/dm)",
  "maestro de educacion visual inicial (mvi)",
  "maestro de expresión corporal inicial (mei)",
  "maestro de expresión manual primaria (mmp)",
  "maestro de expresión plástica primaria (mpp)",
  "maestro de expresión plástica primaria de adultos (mpa)",
  "maestro de expresión plástica primaria de especial (mpe)",
  "maestro de grado (/mg)",
  "maestro de huerta y granja (/hg)",
  "maestro de iniciacion musical-escuelas de estetica (mim)",
  "maestro de irregulares mentales (/im)",
  "maestro de musica 2 hs cat (2ui)",
  "maestro de musica-apoyo rama inicial (mui)",
  "maestro de música 3 hs cat (3ui)",
  "maestro de música primaria (mup)",
  "maestro de música primaria de adultos (mua)",
  "maestro de música primaria de especial (mue)",
  "maestro de orientacion manual (/om)",
  "maestro de pre-taller de jardineria (/jd)",
  "maestro de pre-taller de mantenimiento i (/tu)",
  "maestro de pre-taller de mantenimiento ii (/ms)",
  "maestro de sordos e hipoacusicos (/sh)",
  "maestro de taller (/ta)",
  "maestro de taller de carpinteria (/ca)",
  "maestro de taller de confeccion (/cf)",
  "maestro de taller de construcciones (/cn)",
  "maestro de taller de integracion laboral (/la)",
  "maestro de taller de marroquineria (/mq)",
  "maestro de taller de mecanica (/tm)",
  "maestro de taller de peluqueria (/pl)",
  "maestro de taller de servicios (/ts)",
  "maestro de taller de tejido (/tj)",
  "maestro de teatro inicial (mti)",
  "maestro de teatro primaria (mtp)",
  "maestro de teatro primaria de especial (mte)",
  "maestro domiciliario (/td)",
  "maestro educ.fisica apoyo rama especial. (/ze)",
  "maestro educ.fisica para 1º y 2º ciclo egb (/zp)",
  "maestro educación visual 2 hs cat (2vi)",
  "maestro educación visual 3 hs cat (3vi)",
  "maestro esp. intérprete pedag. lengua señas arg (lsa)",
  "maestro especial (/me)",
  "maestro especializado en grupos: inicial (/gi)",
  "maestro especializado en grupos: primario (/gp)",
  "maestro estimulador (/et)",
  "maestro expresion corporal escuelas educ.estetica (mec)",
  "maestro expresion dramatica escuelas educ.estetica (med)",
  "maestro expresion plastica bi-dimensional (mpb)",
  "maestro expresion plastica tri-dimensional (mpt)",
  "maestro expresión corporal 2 hs cat (2ei)",
  "maestro expresión corporal 3 hs cat (3ei)",
  "maestro intensificador [prog. res. 2275/22] (mai)",
  "maestro pretaller economia domest.y cuidados pers. (/ed)",
  "maestro recuperador (/mr)",
  "maestro seccion (/ma)",
  "maestro severos trastornos de la personalidad (/tp)",
  "maestro teatro 2 hs cat (2ti)",
  "maestro/a de formación general (/fg)",
  "mandos y automatismos (mya)",
  "manifestaciones culturales (mnc)",
  "mantenimiento de instalaciones (min)",
  "mantenimiento eléctrico (mae)",
  "mantenimiento y montaje electromecánico (mme)",
  "maquinarias agricolas/instalaciones rurales (mar)",
  "maquinas eléctricas y automatismos  (mea)",
  "marketing de servicios (mks)",
  "matematica (m.a)",
  "matematica (mtm)",
  "matemática - ciclo superior (mcs)",
  "matemática 1 - 2 (c4i)",
  "matemática aplicada (map)",
  "matemática discreta (mdi)",
  "materiales de obra (mao)",
  "mecánica (mca)",
  "mecánica agrícola (gri)",
  "mecánica y mecanismos (mos)",
  "medicina (m.d)",
  "mediciones equip. e instalaciones electromecanicas (ele)",
  "medico clinico - medico pediatra (/dd)",
  "medico especialista en rehabilitacion (/si)",
  "medico orientador (/do)",
  "metodologia de la investigacion (cms)",
  "metodologia de la investigacion (cna)",
  "metodologia de la investigacion (so1)",
  "microbiología de los alimentos (mic)",
  "modelos y sistemas (mys)",
  "montaje de proyectos electrónicos (mel)",
  "morfologia sonora (mfs)",
  "morfologia visual (mov)",
  "motores de combustión interna (mci)",
  "musica (amc)",
  "musica-apreciacion (*3c)",
  "musica-clarinete (*3u)",
  "musica-coordinacion de conjunto (*9a)",
  "musica-educacion musical (*9c)",
  "musica-elementos tecnicos (*3f)",
  "musica-elementos tecnicos (*9e)",
  "musica-frances (*3n)",
  "musica-guitarra (*3s)",
  "musica-iniciacion (*3a)",
  "musica-italiano (*3o)",
  "musica-piano (*3r)",
  "musica-practica de conjunto (*3b)",
  "musica-viola (*8d)",
  "musica-violin (*8e)",
  "musica-violin (*8r)",
  "musicoterapeuta (/7d)",
  "máquinas eléctricas (maq)",
  "máquinas eléctricas y aplicaciones (mqe)",
  "máquinas y eementos para maniobra, elevación y transporte (mmt)",
  "máquinas y equipos (mye)",
  "mécanica agrícola (mag)",
  "neuropsicopatologia (pq1)",
  "nticx (nti)",
  "nutricion: vidas saludables y etapas de la vida (cnn) (cnn)",
  "observatorio de comunicación cultura y sociedad (ocs)",
  "observatorio de medios (odm)",
  "oleaginosas y cultivos industriales (oci)",
  "op-administración agraria (ada)",
  "op-producción de agroalimentos (pag)",
  "op-producción de carnes (pdc)",
  "op-producción de cereales, oleaginosas y cultivos industriales (pco)",
  "operaciones uni. y tecnología de los materiales (out)",
  "operaciones unitarias y representación gráfica (oug)",
  "operadores y sistemas mecánicos (ops)",
  "organizacion y gestion de la produccion agrop. (oga)",
  "organización de la producción agropecuaria (apo)",
  "organización industrial (oi)",
  "organización industrial y servicios (ois)",
  "organización y gestión del trabajo y la producción (gtp)",
  "organización y gestión industrial (ogi)",
  "organización y métodos (oym)",
  "orientador educacional (/oe)",
  "orientador educacional (secundaria) (soe)",
  "orientador social (/os)",
  "orientador social (secundaria) (sos)",
  "ot-administración agraria (adt)",
  "ot-producción de agroalimentos (pat)",
  "ot-producción de carne (pnt)",
  "ot-producción frutícola y forestal (ptt)",
  "panorama de la produccion contemporanea en danza (ycd)",
  "panorama de la produccion musical contemporanea (ypp)",
  "panorama de la produccion musical popular argentina y latino americana (ypm)",
  "patrimonio turístico nacional e internacional (ptu)",
  "pedagogia (ped)",
  "pedagogico didactica (ce1)",
  "percusion popular (yep)",
  "planeamiento (pla)",
  "planeamiento y evaluación de proyectos (pep)",
  "planificación de obra (pob)",
  "plastica (p.b)",
  "plastica - visual (apv)",
  "plastica-administracion cultural (*1p)",
  "plastica-comunicacion (*1k)",
  "plastica-dibujo (*1f)",
  "plastica-grafica (*1h)",
  "plastica-historia (*1j)",
  "plastica-pintura (*1a)",
  "plastica-pintura (*2g)",
  "politicas publicas y promocion comunicativa 1-2 (c2p) (c2p)",
  "política y ciudadanía (pyc)",
  "portugues (p.g)",
  "portugués (por)",
  "pp-producción de agroalimentos (p05)",
  "pp-producción de carnes (p01)",
  "pp-producción de leche (p02)",
  "pp-producción hortícola y florícola (p06)",
  "practica de conjuntos vocales e instrumentales (yci)",
  "practica docente egb (p.d)",
  "practica docente egb3 y polimodal (ce2)",
  "practica docente ii (taller) (pd2)",
  "practicas del lenguaje (plg)",
  "practicas turisticas (tpt)",
  "preceptor (/pr)",
  "preceptor (pr)",
  "preceptor (pra)",
  "preceptor de institutos terciarios artistica (prt)",
  "preceptor de jardin maternal (/pm)",
  "preceptor escuelas de estetica (pee)",
  "primera disciplina / lenguaje de la orientación 1 -2: teatro  (cat)",
  "problemas socioambientales - soberanía alimentaria y derecho a la alimentación (cww)",
  "problematica social argentina (cpp)",
  "problematicas del desarrollo latinoamericano (plt)",
  "problemática social artentina 1-2 (cpp) (cpp)",
  "procedimientos técnicos (pce)",
  "procedimientos técnicos (pcs)",
  "procedimientos técnicos (pct)",
  "procedimientos técnicos (pt1)",
  "procedimientos técnicos (pt2)",
  "procesamiento mecánico (pmo)",
  "procesos químicos y control (pqc)",
  "produc. y analisis de la imagen (yai)",
  "produccion musical grupal i, ii y iii (ymg)",
  "producción y análisis de la imagen (pai)",
  "producción y comercio exterior (pre)",
  "producción y utilización de forrajes (puf)",
  "prof. de c.e.f. (/ef)",
  "prof.educ.fisica apoyo rama adultos (/za)",
  "profesor de teatro 3° ciclo egb especial (pts)",
  "profesor educ.fisica apoyo a rama inicial. (/zi)",
  "profesor educ.fisica apoyo a rama psicologia (/zs)",
  "profesor educacion fisica apoyo rama inicial 2 hs (2zi)",
  "profesor plastica 3ª ciclo egb adultos (ppa)",
  "profesor/a de ciencias naturales -resol.1873/22 (ps3)",
  "profesor/a de ciencias sociales - resol.1873/22 (ps4)",
  "profesor/a de inglés res. 1873/22 (ps7)",
  "profesor/a de matemática -resol.1873/22 (ps1)",
  "profesor/a de prácticas del lenguaje - resol.1873/22 (ps2)",
  "programacion de objetos y taller de multimedia (cpr)",
  "programación de circuitos (prc)",
  "proyec.y produc.c/art ttp informatica pers.y prof. (-2d)",
  "proyecto (orp)",
  "proyecto 7mo tecnica (p7t)",
  "proyecto de implementación de sitios web dinámicos (pwd)",
  "proyecto de produccion  (ydp)",
  "proyecto de produccion en artes visuales (yav)",
  "proyecto de producción en artes visuales (pav)",
  "proyecto de producción en danza (ppd)",
  "proyecto de producción en literatura (ppl)",
  "proyecto de producción en música (ppm)",
  "proyecto de producción en teatro (ppt)",
  "proyecto final (prf)",
  "proyecto tecnica (pt0)",
  "proyecto y diseño electromecánico (pdn)",
  "proyecto y diseño electrónico (pye)",
  "proyecto, diseño e instalaciones de energías renovables (pd6)",
  "proyectos de artistica (par)",
  "proyectos de educacion agraria (pea)",
  "proyectos de instalaciones (pin)",
  "proyectos de investigación en ciencias sociales (pic)",
  "proyectos de superior (psu)",
  "proyectos organizacionales (pro)",
  "prácticas corporales y dep en el ambiente natural (pcd)",
  "prácticas de conjuntos vocales e instrumentales (pci)",
  "prácticas del lenguaje 1 - 2 (c4b)",
  "prácticas deportivas y acuáticas (pdo)",
  "prácticas deportivas y atléticas (pdi)",
  "prácticas deportivas y juegos (pdj)",
  "prácticas gimnásticas y expresivas (pge)",
  "psicologia (p.s)",
  "psicologia del aprendizaje (psa)",
  "psicologia social (p.c)",
  "psicologia social del turismo (sst)",
  "psicologia social e institucional (pc1)",
  "psicologo (/po)",
  "psicología (psi)",
  "psicología del desarrollo - psicología social e institucional (c4s)",
  "psicopedagogia (p.p)",
  "quimica (qmc)",
  "quimica y su enseñanza (q.e)",
  "quimica: tecnoligia y sociedad (cqq) (cqq)",
  "química analítica (qan)",
  "química del carbono (qdc)",
  "química general e inorgánica (qgi)",
  "química industrial (qi)",
  "química orgánica (qo)",
  "química orgánica biológica (qob)",
  "química orgánica y biológica (alim) (qoa)",
  "realización audiovisual (7° año) (rau)",
  "rectificación de motores (rmo)",
  "recursos lingüísticos (rli)",
  "relaciones públicas protocolo y ceremonial (rpp)",
  "relevamiento ambiental (rea)",
  "resistencia y ensayos de los materiales (rem)",
  "salud (s.a)",
  "salud y adolescencia (sya)",
  "salud y cultura 1 - 2 (cao)",
  "salud: genero y trabajo (css) (css)",
  "seguridad e higiene (s.h)",
  "seguridad informática (ins)",
  "seminario de accesibilidad turistica (sat)",
  "seminario de investigación literaria (sil)",
  "seminario turismo y sustentabilidad (sty)",
  "servicios turísticos (stu)",
  "sistema electroenergético (sle)",
  "sistemas autotrónicos (sa)",
  "sistemas constructivos  i  -  ii (sct)",
  "sistemas constructivos (sco)",
  "sistemas contables - gestión contable de emprendimientos (c2r)",
  "sistemas de comunicaciones (sc)",
  "sistemas de gestión y autogestión (sga)",
  "sistemas de información contable (sic)",
  "sistemas de inyección (si)",
  "sistemas de transmisión (str)",
  "sistemas digitales (sd)",
  "sistemas hidráulicos y neumáticos (shn)",
  "sistemas mecánicos (sm)",
  "sistemas multimediales (6° año) (sim)",
  "sistemas productivos (sp)",
  "sistemas tecnológicos (st1)",
  "sistemas tecnológicos (st2)",
  "sistemas tecnológicos (st3)",
  "sistemas tecnológicos (st4)",
  "sistemas tecnológicos (sts)",
  "sociologia (s.o)",
  "sociologia 1-2 (c4w) (c4w)",
  "sociologia y procesos organizacionales en salud 1-2 (csp) (csp)",
  "sociología (soc)",
  "sociología 1 - 2 (caw)",
  "síntesis de imagen y animación (sia)",
  "taller de composicion  (ydc)",
  "taller de comunicación institucional y comunitaria (tci)",
  "taller de escritura (tde)",
  "taller de literatura y escritura (tle)",
  "taller de percusion  (ytn)",
  "taller de prod. tridimen. (yty)",
  "taller de produc. en dibujo e ilustracion  (yti)",
  "taller de produc. en grabado y arte impreso (yga)",
  "taller de produc. en pintura (ytp)",
  "taller de produc. escultura y ceramica o arte del fuego (yar)",
  "taller de produccion literaria (ypl)",
  "taller de producción en lenguajes (ocl)",
  "taller rural (tru)",
  "teatro (*2a)",
  "teatro (*2b)",
  "teatro (att)",
  "teatro (yte)",
  "tecnico docente medico (tdm)",
  "tecnolog. electrónicas (téc.informát.prof.y pers.) (tee)",
  "tecnología de la información turística (tit)",
  "tecnología de las energías renovables (4°, 5° y 6° año) (ter)",
  "tecnología electrónica (técnico en electrónica) (tel)",
  "tecnología mecánica (tem)",
  "tecnología y producción gráfica (tpg)",
  "tecnología y prácticas digitales 1- 2 (c3z)",
  "tecnologías de la información de la gestión (tig)",
  "teleinformática (tli)",
  "teoria del turismo (ttt)",
  "teoria e historia de los procesos artisticos i, ii, iii y iv (ypa)",
  "teoria politica 1 (tp1)",
  "teoría de las organizaciones (tdo)",
  "teoría y técnica impositiva (tti)",
  "teorías de la comunicación (tlc)",
  "terapista ocupacional (/to)",
  "termodinámica (tdn)",
  "termodinámica y máquinas térmicas (tmt)",
  "trabajo corporal (yrc)",
  "trabajo social (t.s)",
  "trabajo y ciudadanía (tyc)",
  "trayectorias educativas de jovenes y adultos (tja)",
  "turismo e identidad, turrismo: protocolo y organización- gastronomia-desarrollo socioeconomico (c5t) (c5t)",
  "turismo y desarrollo sustentable - política y legislación en turismo  (ca5)",
  "técnicas de diagnóstico (ted)",
  "unión y conformación de os materiales (uyc)",
  "uso y desarrollo de aplicaciones 1-2 (cuu) (cuu)",
  "verano c.e. educacion fisica (cef)",
  "verano c.e. maestros especial (cee)",
  "vivero (vvr)",
  "ética y deontología profesional (edp)",
];

export const CARGO_LABELS = [
  "Derecho Económico y del Trabajo (CTA)",
  "FinEs Educación Artística: Danza (WDZ)",
  "FinEs Educación Artística: Música (WMC)",
  "FinEs Educación Artística: Plástica (WPV)",
  "FinEs Educación Artística: Teatro (WTT)",
  "FinEs Educación Física (WFC)",
  "4ta Proyecto, Diseño e Instalaciones de Energías Renovables (PD4)",
  "5ta Proyecto, Diseño e Instalaciones de Energías Renovables (PD5)",
  "Abordaje de la Interpretacion (YDI)",
  "Actuación (A.C)",
  "Actuación (CTU)",
  "Actuación y Procedimientos Constructivos en Teatro (POC)",
  "Administracion (A.D)",
  "Administracion de Capacidades-Gestion Econimico Comercial (CAG)",
  "Administración y Gestión de los Recursos Humanos (ARH)",
  "Agroalimentos (AGA)",
  "Alimentos (A.L)",
  "Ambiente, Desarrollo y Sociedad (ADS)",
  "Análisis del Lenguaje Teatral (YEA)",
  "Análisis y Producción en Música (YEM)",
  "Antropología (A.N)",
  "Antropología y Cultura (AN2)",
  "Análisis Coreográfico (COR)",
  "Análisis de Modelos Circuitales (MOC)",
  "Análisis de Producción en Música (PEM)",
  "Análisis del Lenguaje Teatral (TEA)",
  "Análisis Matemático (AM)",
  "Aplicaciones de Electrónica Analógica (AEA)",
  "Aplicaciones de Electrónica Digital (AED)",
  "Área Administración (/2A)",
  "Área Administración CENS - Adultos (+2A)",
  "Área Antropología CENS - Adultos (+2G)",
  "Área Ciencias Biológicas CENS - Adultos (+3A)",
  "Área Ciencias de la Educación CENS - Adultos (+2O)",
  "Área Comunicación CENS - Adultos (+3E)",
  "Área Contabilidad CENS - Adultos (+2R)",
  "Área Cs. Políticas y Jurídicas CENS - Adultos (+2U)",
  "Área Economía CENS - Adultos (+3G)",
  "Área Filosofía CENS - Adultos (+3P)",
  "Área Física CENS - Adultos (+5X)",
  "Área Historia CENS - Adultos (+3W)",
  "Área Informática CENS - Adultos (+3Z)",
  "Área Inglés CENS - Adultos (+4F)",
  "Área Inglés de la Educación General Básica-EGB (/AI)",
  "Área Lengua y Literatura CENS - Adultos (+4B)",
  "Área Matemática CENS - Adultos (+4I)",
  "Área Medicina CENS - Adultos (+4O)",
  "Área Psicología CENS - Adultos (+4S)",
  "Área Química CENS - Adultos (+5Y)",
  "Área Sociología CENS - Adultos (+4W)",
  "Área Tecnología CENS - Adultos (+3D)",
  "Áreas de Centro de Producción Total (CPT)",
  "Arte (Leng. Compl. de la Danza): Artes Visuales (CD3)",
  "Arte (Leng. Compl. de la Danza): Música (CD2)",
  "Arte (Leng. Compl. de la Danza): Teatro (CD1)",
  "Arte (Leng. Compl. de la Lit.): Artes Visuales (CL2)",
  "Arte (Leng. Compl. de la Lit.): Danza (CL3)",
  "Arte (Leng. Compl. de la Lit.): Música (CL4)",
  "Arte (Leng. Compl. de la Literatura): Teatro (CL1)",
  "Arte (Leng. Compl. de la Música): Artes Visuales (CM2)",
  "Arte (Leng. Compl. de la Música): Danza (CM3)",
  "Arte (Leng. Compl. de la Música): Teatro (CM1)",
  "Arte (Leng. Compl. de las Artes Visuales): Danza (CA3)",
  "Arte (Leng. Compl. de las Artes Visuales): Música (CA2)",
  "Arte (Leng. Compl. de las Artes Visuales): Teatro (CA1)",
  "Arte (Leng. Compl. del Teatro): Danza (CT3)",
  "Arte (Leng. Compl. del Teatro): Artes Visuales (CT2)",
  "Arte (Leng. Compl. del Teatro): Música (CT1)",
  "Arte (RTE)",
  "Arte Digital y Diseño Web (ADW)",
  "Asistente Educacional (*AE)",
  "Asistente Social (*AS)",
  "Auditoría y Control de Gestión (AUD)",
  "Ayudante del Área Música en Danza Clásica (M7A)",
  "Ayudante del Área Música-Canto (A3K)",
  "Ayudante del Área Música-Iniciación (A3A)",
  "Ayudante del Área Música-Práctica de Conjunto (A3B)",
  "Bases de Datos (BDD)",
  "Bibliotecario (/BE)",
  "Bibliotecario (/BI)",
  "Bibliotecario (/BP)",
  "Bibliotecario (BLA)",
  "Bibliotecario de CENS (/BA)",
  "Bibliotecario de CIE (BIE)",
  "Bibliotecario Institutos Terciarios Artística (BLI)",
  "Bibliotecario Nivel Inicial (/BJ)",
  "Biología (B.G)",
  "Biología (BLG)",
  "Biología y su Enseñanza (B.P)",
  "Biología y Ambiente - Biología y Salud (C3A)",
  "Biología, Genética y Sociedad (BGS)",
  "C.E.: Administración de Capacidades - Gestión Económico Comercial (JAG)",
  "C.E.: Bases de Datos y Proyecto de Software Libre (JBP)",
  "C.E.: Bibliotecario en Contexto de Encierro (JBI)",
  "C.E.: Biología y Ambiente / Biología y Salud (J3A)",
  "C.E.: Ciencias Sociales 1 y 2 (JVW)",
  "C.E.: Ciudadanía, Sociedad y Cultura - Relaciones Laborales y Orientación Profesional (J2U)",
  "C.E.: Comunicación y Cultura (JCC)",
  "C.E.: Derecho Ambiental y Políticas Ambientales (JDA)",
  "C.E.: Derecho Económico y del Trabajo (JET)",
  "C.E.: Derechos Humanos (JDH)",
  "C.E.: Desarrollo Sustentable 1 y 2 (JAL)",
  "C.E.: Economía y Economía Popular, Social y Solidaria (JEE)",
  "C.E.: Educación Artística 1 y 2 Plástica (JPV)",
  "C.E.: Educación Artística 1 y 2 Teatro (JAT)",
  "C.E.: Educación Física 1 y 2 (JFC)",
  "C.E.: Filosofía (JFF)",
  "C.E.: Física: Fenómenos Naturales y Procesos Productivos (J5X)",
  "C.E.: Gestión del Diseño de Emprendimientos/Administración Pública (J2A)",
  "C.E.: Historia-Geografía (JHG)",
  "C.E.: Inglés (JIN)",
  "C.E.: Legislación y Práctica Impositiva - Herramientas Legales para Emprendimientos (JLH)",
  "C.E.: Lengua Adicional Inglés (J4F)",
  "C.E.: Maestro Bibliotecario (JMB)",
  "C.E.: Maestro de Ciclo (JCL)",
  "C.E.: Matemática (JMA)",
  "C.E.: Matemática 1 y 2 (J4I)",
  "C.E.: Metodología de la Investigación (JMM)",
  "C.E.: Preceptor (JPK)",
  "C.E.: Primera Disciplina / Lenguaje de la Orientación 1 y 2 Teatro (JLT)",
  "C.E.: Probl. Social Contemporánea (JHP)",
  "C.E.: Problemática Social Argentina (JPP)",
  "C.E.: Proyecto de Producción Teatro - Proyecto Producción (JJT)",
  "C.E.: Prácticas del Lenguaje 1 y 2 (J4B)",
  "C.E.: Química (JQU)",
  "C.E.: Salud: Género y Trabajo (JSS)",
  "C.E.: Sistemas Contables/Gestión Contable de Emprendimientos (J2R)",
  "C.E.: Sociología (JSO)",
  "C.E.: Sociología 1 y 2 (J4W)",
  "C.E.: Tecnología y Prácticas Digitales 1 y 2 (J3Z)",
  "Canto Coral (YCN)",
  "Canto Popular (YCR)",
  "Capital Humano y Relaciones Laborales (CHR)",
  "Centrales Eléctricas (CEN)",
  "Cereales (CER)",
  "Ciencias de la Educación (C.E)",
  "Ciencias de la Tierra (CDT)",
  "Ciencias Naturales (CNT)",
  "Ciencias Políticas (C.P)",
  "Ciencias Sociales (CSC)",
  "Ciencias Sociales 1 -2 (CVW)",
  "Ciudadanía, Sociedad y Cultura - Relaciones Laborales y Orientación Profesional (C2U)",
  "Cobertura de Asignaturas Formación Profesional (FPG)",
  "Combustión de los Motores Endotérmicos (MOE)",
  "Comportamiento de las Estructuras (CDE)",
  "Comunicación Social (C.S)",
  "Comunicación y Cultura 1-2 (CCC)",
  "Comunicación y Culturas del Consumo (CYC)",
  "Comunicación y Transf. Socioculturales Siglo XXI (CYT)",
  "Comunicación, Cultura y Sociedad (CCS)",
  "Conocimiento de los Materiales (M. Mayor de Obras) (CMM)",
  "Conocimiento de los Materiales (Téc. Automotores) (CMA)",
  "Conocimiento de los Materiales (Téc. Electromec.) (CME)",
  "Construcción de Ciudadanía (CCD)",
  "Contables (C.B)",
  "Controles y Automatismo (4°, 5° y 6° Año) (CYA)",
  "Coordinador Institucional (COI)",
  "Coordinador Institucional de Trayectorias Educativas (CIT)",
  "Costos (COS)",
  "Danza (ADZ)",
  "Danza Clásica I, II, III y IV (YCL)",
  "Danza Folklórica y Popular I, II, III, IV y V (YFP)",
  "Danzas Expresión Corporal (*7C)",
  "Danzas Tradicionales Argentinas (*7B)",
  "Deportes Abiertos (D.A)",
  "Derecho (DER)",
  "Derecho (DRC)",
  "Derecho Administrativo (D.D)",
  "Derecho Ambiental y Políticas Ambientales (CDP)",
  "Derecho Civil (D.C)",
  "Derecho Comercial (D.M)",
  "Derecho del Trabajo y Seguridad Social (D.T)",
  "Derecho Penal (D.P)",
  "Derechos del Trabajo (DET)",
  "Derechos Humanos 1-2 (CDH)",
  "Derechos Humanos y Ciudadanía (DHU)",
  "Desarrollo de Aplicaciones Web Dinámicas (DWD)",
  "Desarrollo de Aplicaciones Web Estáticas (DWE)",
  "Desarrollo Regional (CRD)",
  "Desarrollo Sustentable 1 - 2 (CAL)",
  "Destinos Turísticos (TDT)",
  "Dibujo Tecnológico (Maestro Mayor de Obras) (DTM)",
  "Dibujo Tecnológico (Técnico Automotores) (DTA)",
  "Dibujo Tecnológico (Técnico Electromecánica) (DTE)",
  "Didáctica de la Biología (DBI)",
  "Didáctica de las Ciencias Naturales (DCN)",
  "Didáctica de las Ciencias Sociales - Historia (DCH)",
  "Didáctica y Curriculum (DYC)",
  "Difícil Cobertura (DCA)",
  "Dinámica de Grupos (PC2)",
  "Dirección de la Ejecución de Instalaciones (DEJ)",
  "Director (XXD)",
  "Director de Escuela de Verano (DEV)",
  "Diseño Asistido y Simulación Electrónica (DAS)",
  "Diseño de Emprendimientos Turísticos (CJF)",
  "Diseño y Gestión de Proyectos Turísticos Sociocomunitarios (DGP)",
  "Diseño y Gestión de Proyectos (DIS)",
  "Diseño y Procesamiento Mecánico (PRM)",
  "Docente Coordinador/a de Trayectorias - Resol.1873/22 (PS6)",
  "Docente Integrador de Círculos y Trayectorias (D8D)",
  "Documentación Técnica (DOT)",
  "Economía y Economía Popular, Social y Solidaria (CEC)",
  "Economía (ENO)",
  "Economía Política (EPO)",
  "Educación (*4A)",
  "Educación Física (E.F)",
  "Educación Física (EFC)",
  "Educación Física y su Enseñanza (E.D)",
  "Educación Artística 1-2: Música (CMC)",
  "Educación Artística 1-2 : Danza (CDZ)",
  "Educación Artística 1-2: Plástica (CPV)",
  "Educación Artística 1-2: Teatro (CTT)",
  "Educación Física 1-2 (CFC)",
  "Educación Física y Comunidad (EFU)",
  "Educación Física y Corporeidad (FCO)",
  "Educación Física y Cultura (EFI)",
  "Eficiencia Energética y Uso Racional de la Energía (EER)",
  "Ejercicio Profesional de la Construcción (EPC)",
  "Electrotecnia (NIA)",
  "Electrotecnia del Automotor (EAU)",
  "Electrotecnia y Electrónica (T.E.I.E.) (-6K)",
  "Electrónica (ECT)",
  "Electrónica Aplicada (ELA)",
  "Electrónica Industrial (EIN)",
  "Electrónica y Autotrónica (NIC)",
  "Elementos de Micro y Macro Economía (EMM)",
  "EMATP Tecnología de la Leche (ETL)",
  "Emprendimientos Productivos y Desarrollo Local (EDL)",
  "Enc. de Medios de Apoyo Téc-Pedag. en C. Sociales (ECS)",
  "Enc. de Medios de Apoyo Téc-Pedag. Especialidad Taller (/PA)",
  "Encarg. de Medios de Apoyo Téc.-Pedag. Area Informatica (PLI)",
  "Encargado Medios Apoyo Téc-Ped. CS Fisicas (EFF)",
  "Encargado Medios Apoyo Téc-Ped. Biología (EBB)",
  "Encargado Medios Apoyo Téc-Ped. Comunic. Arte y Dis (EAD)",
  "Encargado Medios Apoyo Téc-Ped. Construc. Civiles (ECO)",
  "Encargado Medios Apoyo Téc-Ped. Econ. y Ges. Organiza (ELC)",
  "Encargado Medios Apoyo Téc-Ped. Electrónica (EEL)",
  "Encargado Medios Apoyo Téc-Ped. Inf/Comp/E Inf. Apl. (ELI)",
  "Encargado Medios Apoyo Téc-Ped. Med/Equip/Ins. Elec. (ELD)",
  "Encargado Medios Apoyo Téc-Ped. Química (EQQ)",
  "Encargado Medios Apoyo Téc-Ped. Biología (EBB)",
  "Escenoplastica (YSC)",
  "Escuela de Verano Contexto de Encierro (CEV)",
  "Escuela de Verano Educación Física (VEF)",
  "Escuela de Verano Guardavida (VGU)",
  "Espacio Complementario (Escultura) (YCE)",
  "Espacio Complementario (Grabado) (YCG)",
  "Espacio de la Especialidad (Grabado) (YEG)",
  "Espacio de la Especialidad (Pintur) (YPI)",
  "Espacio de Profundizacion del Aprendizaje (EPA)",
  "Espacios Turísticos de la Argentina (ETA)",
  "Estructuras (ESR)",
  "Estudios Interculturales en Inglés (EST)",
  "Filosofia (*6A)",
  "Filosofia (F.I)",
  "Filosofia (FIA)",
  "Filosofia 1-2 (CFF)",
  "Filosofía (FIA)",
  "Filosofía e Historia de la Ciencia y la Tecnología (FCT)",
  "Fines Administración Pública, de Capacidades y Relaciones Laborales 2do Año (WAA)",
  "Fines Biología (WCB)",
  "Fines Ciudadanía, Sociedad, Cultura y Relaciones Laborales 2do Año (WCR)",
  "Fines Comunicación y Cultura 3er Año (WCC)",
  "Fines Comunicación y Medios (WCM)",
  "Fines Contabilidad (WCO)",
  "Fines Derecho (WDD)",
  "Fines Derechos Humanos 2do Año (WDH)",
  "Fines Educación Artística: Literatura y Escritura (WLE)",
  "Fines Educación Artística: Música (WMC)",
  "Fines Educación Artística: Plástica (WPV)",
  "Fines Educación Física (WFC)",
  "Fines Filosofía 3er Año (WFP)",
  "Fines Física (WFF)",
  "Fines Fundamentos de Economía y Perspectiva Popular, Social y Solidaria 3er Año (WEG)",
  "Fines Historia y Geografía (WHG)",
  "Fines Informática (WIF)",
  "Fines Inglés (WIN)",
  "Fines Legislación Impositiva y Herramientas para Emprendimientos 3er Año (WRU)",
  "Fines Lengua y Literatura (WLL)",
  "Fines Matemática (WMT)",
  "Fines Metodología de la Investigación (WMI)",
  "Fines Planificación y Gestión de Emprendimientos (Esp. 2º) (WPG)",
  "Fines Práctica Contable Laboral e Impositiva (Esp. 3º) (WPC)",
  "Fines Problemática Social Argentina 3er Año (WSP)",
  "Fines Problemática Social Contemporánea (WPS)",
  "Fines Psicología (WPA)",
  "Fines Química (WQQ)",
  "Fines Sociología (WSS)",
  "Física y su Enseñanza (F.T)",
  "Física: Fenómenos Naturales y Procesos Productivos (C5X)",
  "Físico - Química (FQA)",
  "Fonoaudiología (F.N)",
  "Fonoaudiólogo (/FO)",
  "Forrajes (FRJ)",
  "Fortalecimiento de Trayectorias Educativas (Inicial) (MIF)",
  "Fortalecimiento de Trayectorias Educativas (Primaria) [Prog. Res. 417/21- 3206/21- 446/22 ] (MGF)",
  "Fotografía (YOT)",
  "Francés (FRA)",
  "Fundamentos de la Química (FDQ)",
  "Fundamentos de los Modelos Circuitales (FMC)",
  "Fundamentos y Modelos de Mecánica Clásica (FMM)",
  "Física (FIS)",
  "Física Clásica y Moderna (FCM)",
  "Ganadería (GND)",
  "Ganadería de Carne (GCA)",
  "Ganadería de Leche (GDL)",
  "Genética y Evolución (G.E)",
  "Geografía (G.F)",
  "Geografía (GGF)",
  "Geografía de Género (GGE)",
  "Geografía y su Enseñanza (G.P)",
  "Gestión Comercial (GCO)",
  "Gestión de la Producción (GES)",
  "Gestión de las Energías Renovables (GER)",
  "Gestión de Proyectos (GDP)",
  "Gestión de Proyectos (GPR)",
  "Gestión del Diseño de Emprendimientos - Administración Pública (C2A)",
  "Gestión Financiera Bancaria y Seguros (FIN)",
  "Gestión Organizacional (GOR)",
  "Granja 1º y 2º Año (GRA)",
  "Gráfica Editorial (GRE)",
  "Guardavidas (GU)",
  "Guión (5° Año) (GUI)",
  "Historia (H.I)",
  "Historia (HTR)",
  "Historia Contemporánea (H.C)",
  "Huerta (HUE)",
  "Imagen y Nuevos Medios (INM)",
  "Imagen y Nuevos Medios (YNM)",
  "Imagen y Procedimientos Constructivos (LEP)",
  "Imagen y Procedimientos Constructivos (YIP)",
  "Improvisación y Composición Coreográfica (IMP)",
  "Informática (I.F)",
  "Inglés (I.N)",
  "Inglés (IGS)",
  "Inglés Específico (ING)",
  "Iniciación a la Danza Folklórica y Popular (YDF)",
  "Instalaciones de Baja Tensión y Media Tensión (IBT)",
  "Instalaciones Eléctricas (IE)",
  "Instalaciones Industriales (IIM)",
  "Instalaciones Industriales (IND)",
  "Instalaciones Sanitarias y de Gas (ISI)",
  "Instalaciones y Aplicaciones de la Energía (APE)",
  "Instalaciones y Máquinas Eléctricas (IMO)",
  "Instalación, Mantenimiento y Reparación de Redes Informáticas (IRI)",
  "Instalación, Mantenimiento y Reparación de Sistemas Computacionales (IMC)",
  "Instructor/a de Formación Profesional - Resol.1873/22 (PS5)",
  "Instrumental de Medición (IMU)",
  "Instrumento (YNS)",
  "Instrumento (Piano o Guitarra) (YII)",
  "Instrumento Complementario (YNC)",
  "Instrumento Principal (YNP)",
  "Intensificación Agropecuaria (IA)",
  "Interpretación de Anteproyectos (IAN)",
  "Introducción a los Multimedios (IAM)",
  "Introducción al Portugués (IPO)",
  "Introducción a la Biología Celular (IBC)",
  "Introducción a la Comunicación (IAC)",
  "Introducción a la Electricidad y Mediciones (IEM)",
  "Introducción a la Física (IAF)",
  "Introducción a la Programación Orientada a Objetos (IOO)",
  "Introducción a la Química (IAQ)",
  "Introducción a las Organizaciones (IOR)",
  "Introducción al Turismo - Prestadores Turísticos (C5A)",
  "Introducción al Turismo y Oferta Turística (ITT)",
  "Investigación del Medio 1° y 2° Año (IME)",
  "Investigación Operativa (OPE)",
  "Italiano (ITA)",
  "Jornada Escolar de 25 Horas- Maestro de Apoyo - [Prog. Res. 2502/22] (MA5)",
  "Jornada Escolar de 25 Horas- Maestro de Grado - [Prog. Res. 2502/22] (MG5)",
  "Kinesiólogo (/KI)",
  "Lab. de Op. Unit. y Tecnología de los Materiales (LOT)",
  "Laboratorio de Análisis Microbiológicos (LAM)",
  "Laboratorio de Aplicaciones (LAP)",
  "Laboratorio de Diseño de Bases de Datos (LDB)",
  "Laboratorio de Diseño Web (LDW)",
  "Laboratorio de Ensayo de Motores (ENS)",
  "Laboratorio de Ensayos Físicos (LEF)",
  "Laboratorio de Ensayos Industriaes (LEI)",
  "Laboratorio de Hardware (LHW)",
  "Laboratorio de Mediciones Electricas (LME)",
  "Laboratorio de Metrología y Control de Calidad (LCC)",
  "Laboratorio de Procesos Industriales (LPI)",
  "Laboratorio de Procesos Industriales (PRI)",
  "Laboratorio de Programación (LPR)",
  "Laboratorio de Química Orgánica, Biológica y Microbiológica (QUI)",
  "Laboratorio de Química (LQI)",
  "Laboratorio de Química Orgánica (QOR)",
  "Laboratorio de Química Orgánica, Biológica y Microbiológica (Alimentos) (QUA)",
  "Laboratorio de Redes Informáticas (LRI)",
  "Laboratorio de Sistemas Operativos (LSO)",
  "Laboratorio de Técnicas Analíticas (TEC)",
  "Legislación y Práctica Monetaria-Herramientas Legales para Emprendimientos (CLH)",
  "Lengua (L.N)",
  "Lengua Adicional 1-2: Inglés (C4F)",
  "Lengua y su Enseñanza (L.P)",
  "Lenguaje Complementario (Artes Visuales) (YCA)",
  "Lenguaje Complementario (Danza) (YLZ)",
  "Lenguaje Complementario (Musica) (YCM)",
  "Lenguaje Complementario (Teatro) (YLT)",
  "Lenguaje de la Danza (LED)",
  "Lenguaje Musical (YEN)",
  "Lenguaje Musical (LEN)",
  "Lenguaje Visual I y II (YVL)",
  "Lenguajes Artísticos / Música (LTM)",
  "Lenguajes Artísticos / Plástica (LTP)",
  "Lenguajes Artísticos / Teatro y Diseño Escenográfico (LTT)",
  "Lenguajes Electrónicos (LEE)",
  "Lenguajes Musicales Contemporáneos (YMC)",
  "Lenguajes Tecnológicos (LT1)",
  "Lenguajes Tecnológicos (LT2)",
  "Lenguajes Tecnológicos (LTE)",
  "Lenguajes Tecnológicos (LTS)",
  "Lingüística (L.G)",
  "Literatura (L.T)",
  "Literatura (LIT)",
  "Logística (L.O)",
  "Líneas de Transmisión (LTR)",
  "Ma-Agriultura (AGR)",
  "Ma-Avicultura (AVI)",
  "Ma-Bovinos de Carne (BOC)",
  "Ma-Bovinos de Leche (BOL)",
  "Ma-Cunicultura (CUN)",
  "Ma-Huerta (HOR)",
  "Ma-Mecánica Agrícola (MEG)",
  "Ma-Máquinas, Equipos, Herramientas e Inst. Rurales (MIR)",
  "Ma-Ovinos (OVI)",
  "Ma-Planta de Elaboración de Forrajes (EFO)",
  "Ma-Porcinos (POS)",
  "Ma-Sala de Elaboración de Productos Cárnicos (ECA)",
  "Ma-Sala de Elaboración de Productos Lácteos (EPL)",
  "Ma-Sala de Frutas y Hortalizas (SFH)",
  "Ma-Taller Rural (TRM)",
  "Ma-Vivero (PVI)",
  "Maest. Auxiliar Taller Armado (*RA)",
  "Maest. Auxiliar Taller Carpinteria (*CA)",
  "Maest. Auxiliar Taller Confeccion (*CF)",
  "Maest. Auxiliar Taller Construcciones (*CN)",
  "Maest. Auxiliar Taller Mecanica (*TM)",
  "Maest. Auxiliar Taller Peluqueria (*PL)",
  "Maest. Auxiliar Taller Servicios (*TS)",
  "Maestra Bibliotecaria Rama Adultos (/MB)",
  "Maestra de Infantes (/MI)",
  "Maestra de Jardin Maternal (/JM)",
  "Maestra de Pre-Taller de Costura (/TC)",
  "Maestra Hospitalaria (/DH)",
  "Maestra Iniciacion Literaria Escuelas de Estetica (MIL)",
  "Maestro Alteraciones en el Desarrollo del Lenguaje (/AL)",
  "Maestro Ciegos y Disminuidos Visuales (/DC)",
  "Maestro de Apoyo (MA)",
  "Maestro de Apoyo para Escuelas Laborales (/AB)",
  "Maestro de Armado (/RA)",
  "Maestro de Articulacion (/AR)",
  "Maestro de Ciclo (/MC)",
  "Maestro de Danza Primaria (MDP)",
  "Maestro de Danza Primaria de Especial (MDE)",
  "Maestro de Discapacitados Motores (/DM)",
  "Maestro de Educacion Visual Inicial (MVI)",
  "Maestro de Expresión Corporal Inicial (MEI)",
  "Maestro de Expresión Manual Primaria (MMP)",
  "Maestro de Expresión Plástica Primaria (MPP)",
  "Maestro de Expresión Plástica Primaria de Adultos (MPA)",
  "Maestro de Expresión Plástica Primaria de Especial (MPE)",
  "Maestro de Grado (/MG)",
  "Maestro de Huerta y Granja (/HG)",
  "Maestro de Iniciacion Musical-Escuelas de Estetica (MIM)",
  "Maestro de Irregulares Mentales (/IM)",
  "Maestro de Musica 2 hs Cat (2UI)",
  "Maestro de Musica-Apoyo Rama Inicial (MUI)",
  "Maestro de Música 3 hs Cat (3UI)",
  "Maestro de Música Primaria (MUP)",
  "Maestro de Música Primaria de Adultos (MUA)",
  "Maestro de Música Primaria de Especial (MUE)",
  "Maestro de Orientacion Manual (/OM)",
  "Maestro de Pre-Taller de Jardineria (/JD)",
  "Maestro de Pre-Taller de Mantenimiento I (/TU)",
  "Maestro de Pre-Taller de Mantenimiento II (/MS)",
  "Maestro de Sordos e Hipoacusicos (/SH)",
  "Maestro de Taller (/TA)",
  "Maestro de Taller de Carpinteria (/CA)",
  "Maestro de Taller de Confeccion (/CF)",
  "Maestro de Taller de Construcciones (/CN)",
  "Maestro de Taller de Integracion Laboral (/LA)",
  "Maestro de Taller de Marroquineria (/MQ)",
  "Maestro de Taller de Mecanica (/TM)",
  "Maestro de Taller de Peluqueria (/PL)",
  "Maestro de Taller de Servicios (/TS)",
  "Maestro de Taller de Tejido (/TJ)",
  "Maestro de Teatro Inicial (MTI)",
  "Maestro de Teatro Primaria (MTP)",
  "Maestro de Teatro Primaria de Especial (MTE)",
  "Maestro Domiciliario (/TD)",
  "Maestro Educ.Fisica Apoyo Rama Especial. (/ZE)",
  "Maestro Educ.Fisica para 1º y 2º Ciclo EGB (/ZP)",
  "Maestro Educación Visual 2 hs Cat (2VI)",
  "Maestro Educación Visual 3 hs Cat (3VI)",
  "Maestro Esp. Intérprete Pedag. Lengua Señas Arg (LSA)",
  "Maestro Especial (/ME)",
  "Maestro especializado en grupos: inicial (/GI)",
  "Maestro especializado en grupos: primario (/GP)",
  "Maestro estimulador (/ET)",
  "Maestro Expresión Corporal Escuelas Educ.Estetica (MEC)",
  "Maestro Expresión Dramática Escuelas Educ.Estetica (MED)",
  "Maestro Expresión Plástica Bi-Dimensional (MPB)",
  "Maestro Expresión Plástica Tri-Dimensional (MPT)",
  "Maestro Expresión Corporal 2 hs Cat (2EI)",
  "Maestro Expresión Corporal 3 hs Cat (3EI)",
  "Maestro Intensificador [Prog. Res. 2275/22] (MAI)",
  "Maestro Pretaller Economia Domest.y Cuidados Pers. (/ED)",
  "Maestro Recuperador (/MR)",
  "Maestro Seccion (/MA)",
  "Maestro Severos Trastornos de la Personalidad (/TP)",
  "Maestro Teatro 2 hs Cat (2TI)",
  "Maestro/a de Formación General (/FG)",
  "Mandos y Automatismos (MYA)",
  "Manifestaciones Culturales (MNC)",
  "Mantenimiento de Instalaciones (MIN)",
  "Mantenimiento Eléctrico (MAE)",
  "Mantenimiento y Montaje Electromecánico (MME)",
  "Maquinarias Agrícolas / Instalaciones Rurales (MAR)",
  "Máquinas Eléctricas y Automatismos (MEA)",
  "Marketing de Servicios (MKS)",
  "Matemática (M.A)",
  "Matemática (MTM)",
  "Matemática - Ciclo Superior (MCS)",
  "Matemática 1 - 2 (C4I)",
  "Matemática Aplicada (MAP)",
  "Matemática Discreta (MDI)",
  "Materiales de Obra (MAO)",
  "Mecánica (MCA)",
  "Mecánica Agrícola (GRI)",
  "Mecánica y Mecanismos (MOS)",
  "Medicina (M.D)",
  "Mediciones Equip. e Instalaciones Electromecanicas (ELE)",
  "Médico Clínico - Médico Pediatra (/DD)",
  "Médico Especialista en Rehabilitación (/SI)",
  "Médico Orientador (/DO)",
  "Metodología de la Investigación (CMS)",
  "Metodología de la Investigación (CNA)",
  "Metodología de la Investigación (SO1)",
  "Microbiología de los Alimentos (MIC)",
  "Modelos y Sistemas (MYS)",
  "Montaje de Proyectos Electrónicos (MEL)",
  "Morfología Sonora (MFS)",
  "Morfología Visual (MOV)",
  "Motores de Combustión Interna (MCI)",
  "Música (AMC)",
  "Música-Apreciación (*3C)",
  "Música-Clarinete (*3U)",
  "Música-Coordinación de Conjunto (*9A)",
  "Música-Educación Musical (*9C)",
  "Música-Elementos Técnicos (*3F)",
  "Música-Elementos Técnicos (*9E)",
  "Música-Francés (*3N)",
  "Música-Guitarra (*3S)",
  "Música-Iniciación (*3A)",
  "Música-Italiano (*3O)",
  "Música-Piano (*3R)",
  "Música-Práctica de Conjunto (*3B)",
  "Música-Viola (*8D)",
  "Música-Violín (*8E)",
  "Música-Violín (*8R)",
  "Musicoterapeuta (/7D)",
  "Máquinas Eléctricas (MAQ)",
  "Máquinas Eléctricas y Aplicaciones (MQE)",
  "Máquinas y Elementos para Maniobra, Elevación y Transporte (MMT)",
  "Máquinas y Equipos (MYE)",
  "Mecánica Agrícola (MAG)",
  "Neuropsicopatología (PQ1)",
  "NTICX (NTI)",
  "Nutrición: Vidas Saludables y Etapas de la Vida (CNN)",
  "Observatorio de Comunicación Cultura y Sociedad (OCS)",
  "Observatorio de Medios (ODM)",
  "Oleaginosas y Cultivos Industriales (OCI)",
  "OP-Administración Agraria (ADA)",
  "OP-Producción de Agroalimentos (PAG)",
  "OP-Producción de Carnes (PDC)",
  "OP-Producción de Cereales, Oleaginosas y Cultivos Industriales (PCO)",
  "Operaciones Uni. y Tecnología de los Materiales (OUT)",
  "Operaciones Unitarias y Representación Gráfica (OUG)",
  "Operadores y Sistemas Mecánicos (OPS)",
  "Organización y Gestión de la Producción Agrop. (OGA)",
  "Organización de la Producción Agropecuaria (APO)",
  "Organización Industrial (OI)",
  "Organización Industrial y Servicios (OIS)",
  "Organización y Gestión del Trabajo y la Producción (GTP)",
  "Organización y Gestión Industrial (OGI)",
  "Organización y Métodos (OYM)",
  "Orientador Educacional (/OE)",
  "Orientador Educacional (Secundaria) (SOE)",
  "Orientador Social (/OS)",
  "Orientador Social (Secundaria) (SOS)",
  "OT-Administración Agraria (ADT)",
  "OT-Producción de Agroalimentos (PAT)",
  "OT-Producción de Carne (PNT)",
  "OT-Producción Frutícola y Forestal (PTT)",
  "Panorama de la Producción Contemporánea en Danza (YCD)",
  "Panorama de la Producción Musical Contemporánea (YPP)",
  "Panorama de la Producción Musical Popular Argentina y Latinoamericana (YPM)",
  "Patrimonio Turístico Nacional e Internacional (PTU)",
  "Pedagogia (PED)",
  "Pedagogico Didactica (CE1)",
  "Percusion Popular (YEP)",
  "Planeamiento (PLA)",
  "Planeamiento y Evaluación de Proyectos (PEP)",
  "Planificación de Obra (POB)",
  "Plastica (P.B)",
  "Plastica - Visual (APV)",
  "Plastica-Administracion Cultural (*1P)",
  "Plastica-Comunicacion (*1K)",
  "Plastica-Dibujo (*1F)",
  "Plastica-Grafica (*1H)",
  "Plastica-Historia (*1J)",
  "Plastica-Pintura (*1A)",
  "Plastica-Pintura (*2G)",
  "Politicas Publicas y Promocion Comunicativa 1-2 (C2P)",
  "Politica y Ciudadania (PYC)",
  "Portugues (P.G)",
  "Portugués (POR)",
  "PP-Producción de Agroalimentos (P05)",
  "PP-Producción de Carnes (P01)",
  "PP-Producción de Leche (P02)",
  "PP-Producción Hortícola y Florícola (P06)",
  "Practica de Conjuntos Vocales e Instrumentales (YCI)",
  "Practica Docente EGB (P.D)",
  "Practica Docente EGB3 y Polimodal (CE2)",
  "Practica Docente II (Taller) (PD2)",
  "Practicas del Lenguaje (PLG)",
  "Practicas Turisticas (TPT)",
  "Preceptor (/PR)",
  "Preceptor (PR)",
  "Preceptor (PRA)",
  "Preceptor de Institutos Terciarios Artistica (PRT)",
  "Preceptor de Jardin Maternal (/PM)",
  "Preceptor Escuelas de Estetica (PEE)",
  "Primera Disciplina / Lenguaje de la Orientación 1-2: Teatro (CAT)",
  "Problemas Socioambientales - Soberanía Alimentaria y Derecho a la Alimentación (CWW)",
  "Problematica Social Argentina (CPP)",
  "Problematicas del Desarrollo Latinoamericano (PLT)",
  "Problemática Social Artentina 1-2 (CPP)",
  "Procedimientos Técnicos (PCE)",
  "Procedimientos Técnicos (PCS)",
  "Procedimientos Técnicos (PCT)",
  "Procedimientos Técnicos (PT1)",
  "Procedimientos Técnicos (PT2)",
  "Procesamiento Mecánico (PMO)",
  "Procesos Químicos y Control (PQC)",
  "Produc. y Analisis de la Imagen (YAI)",
  "Produccion Musical Grupal I, II y III (YMG)",
  "Producción y Análisis de la Imagen (PAI)",
  "Producción y Comercio Exterior (PRE)",
  "Producción y Utilización de Forrajes (PUF)",
  "Prof. de C.E.F. (/EF)",
  "Prof.Educ.Fisica Apoyo Rama Adultos (/ZA)",
  "Profesor de Teatro 3° Ciclo EGB Especial (PTS)",
  "Profesor Educ. Física Apoyo a Rama Inicial (/ZI)",
  "Profesor Educ. Física Apoyo a Rama Psicologia (/ZS)",
  "Profesor Educacion Fisica Apoyo Rama Inicial 2 Hs (2ZI)",
  "Profesor Plástica 3ª Ciclo EGB Adultos (PPA)",
  "Profesor/a de Ciencias Naturales - Resol.1873/22 (PS3)",
  "Profesor/a de Ciencias Sociales - Resol.1873/22 (PS4)",
  "Profesor/a de Inglés Res. 1873/22 (PS7)",
  "Profesor/a de Matemática - Resol.1873/22 (PS1)",
  "Profesor/a de Prácticas del Lenguaje - Resol.1873/22 (PS2)",
  "Programacion de Objetos y Taller de Multimedia (CPR)",
  "Programación de Circuitos (PRC)",
  "Proyec.y Produc.C/Art TTP Informatica Pers.y Prof. (-2D)",
  "Proyecto (ORP)",
  "Proyecto 7mo Tecnica (P7T)",
  "Proyecto de Implementación de Sitios Web Dinámicos (PWD)",
  "Proyecto de Produccion (YDP)",
  "Proyecto de Produccion en Artes Visuales (YAV)",
  "Proyecto de Producción en Artes Visuales (PAV)",
  "Proyecto de Producción en Danza (PPD)",
  "Proyecto de Producción en Literatura (PPL)",
  "Proyecto de Producción en Música (PPM)",
  "Proyecto de Producción en Teatro (PPT)",
  "Proyecto Final (PRF)",
  "Proyecto Técnica (PT0)",
  "Proyecto y Diseño Electromecánico (PDN)",
  "Proyecto y Diseño Electrónico (PYE)",
  "Proyecto, Diseño e Instalaciones de Energías Renovables (PD6)",
  "Proyectos de Artistica (PAR)",
  "Proyectos de Educacion Agraria (PEA)",
  "Proyectos de Instalaciones (PIN)",
  "Proyectos de Investigación en Ciencias Sociales (PIC)",
  "Proyectos de Superior (PSU)",
  "Proyectos Organizacionales (PRO)",
  "Prácticas Corporales y Dep en el Ambiente Natural (PCD)",
  "Prácticas de Conjuntos Vocales e Instrumentales (PCI)",
  "Prácticas del Lenguaje 1 - 2 (C4B)",
  "Prácticas Deportivas y Acuáticas (PDO)",
  "Prácticas Deportivas y Atléticas (PDI)",
  "Prácticas Deportivas y Juegos (PDJ)",
  "Prácticas Gimnásticas y Expresivas (PGE)",
  "Psicología (P.S)",
  "Psicología del Aprendizaje (PSA)",
  "Psicología Social (P.C)",
  "Psicología Social del Turismo (SST)",
  "Psicología Social e Institucional (PC1)",
  "Psicólogo (/PO)",
  "Psicología (PSI)",
  "Psicología del Desarrollo - Psicología Social e Institucional (C4S)",
  "Psicopedagogía (P.P)",
  "Química (QMC)",
  "Química y su Enseñanza (Q.E)",
  "Química: Tecnología y Sociedad (CQQ)",
  "Química Analítica (QAN)",
  "Química del Carbono (QDC)",
  "Química General e Inorgánica (QGI)",
  "Química Industrial (QI)",
  "Química Orgánica (QO)",
  "Química Orgánica Biológica (QOB)",
  "Química Orgánica y Biológica (Alim) (QOA)",
  "Realización Audiovisual (7° Año) (RAU)",
  "Rectificación de Motores (RMO)",
  "Recursos Lingüísticos (RLI)",
  "Relaciones Públicas Protocolo y Ceremonial (RPP)",
  "Relevamiento Ambiental (REA)",
  "Resistencia y Ensayos de los Materiales (REM)",
  "Salud (S.A)",
  "Salud y Adolescencia (SYA)",
  "Salud y Cultura 1 - 2 (CAO)",
  "Salud: Género y Trabajo (CSS)",
  "Seguridad e Higiene (S.H)",
  "Seguridad Informática (INS)",
  "Seminario de Accesibilidad Turística (SAT)",
  "Seminario de Investigación Literaria (SIL)",
  "Seminario Turismo y Sustentabilidad (STY)",
  "Servicios Turísticos (STU)",
  "Sistema Electroenergético (SLE)",
  "Sistemas Autotrónicos (SA)",
  "Sistemas Constructivos I - II (SCT)",
  "Sistemas Constructivos (SCO)",
  "Sistemas Contables - Gestión Contable de Emprendimientos (C2R)",
  "Sistemas de Comunicaciones (SC)",
  "Sistemas de Gestión y Autogestión (SGA)",
  "Sistemas de Información Contable (SIC)",
  "Sistemas de Inyección (SI)",
  "Sistemas de Transmisión (STR)",
  "Sistemas Digitales (SD)",
  "Sistemas Hidráulicos y Neumáticos (SHN)",
  "Sistemas Mecánicos (SM)",
  "Sistemas Multimediales (6° Año) (SIM)",
  "Sistemas Productivos (SP)",
  "Sistemas Tecnológicos (ST1)",
  "Sistemas Tecnológicos (ST2)",
  "Sistemas Tecnológicos (ST3)",
  "Sistemas Tecnológicos (ST4)",
  "Sistemas Tecnológicos (STS)",
  "Sociología (S.O)",
  "Sociología 1-2 (C4W)",
  "Sociología y Procesos Organizacionales en Salud 1-2 (CSP)",
  "Sociología (SOC)",
  "Sociología 1 - 2 (CAW)",
  "Síntesis de Imagen y Animación (SIA)",
  "Taller de Composición (YDC)",
  "Taller de Comunicación Institucional y Comunitaria (TCI)",
  "Taller de Escritura (TDE)",
  "Taller de Literatura y Escritura (TLE)",
  "Taller de Percusión (YTN)",
  "Taller de Producción Tridimensional (YTY)",
  "Taller de Producción en Dibujo e Ilustración (YTI)",
  "Taller de Producción en Grabado y Arte Impreso (YGA)",
  "Taller de Producción en Pintura (YTP)",
  "Taller de Producción en Escultura y Cerámica o Arte del Fuego (YAR)",
  "Taller de Producción Literaria (YPL)",
  "Taller de Producción en Lenguajes (OCL)",
  "Taller Rural (TRU)",
  "Teatro (*2A)",
  "Teatro (*2B)",
  "Teatro (ATT)",
  "Teatro (YTE)",
  "Técnico Docente Médico (TDM)",
  "Tecnolog. Electrónicas (Téc.Informát.Prof.y Pers.) (TEE)",
  "Tecnología de la Información Turística (TIT)",
  "Tecnología de las Energías Renovables (4°, 5° y 6° Año) (TER)",
  "Tecnología Electrónica (Técnico en Electrónica) (TEL)",
  "Tecnología Mecánica (TEM)",
  "Tecnología y Producción Gráfica (TPG)",
  "Tecnología y Prácticas Digitales 1- 2 (C3Z)",
  "Tecnologías de la Información de la Gestión (TIG)",
  "Teleinformática (TLI)",
  "Teoría del Turismo (TTT)",
  "Teoría e Historia de los Procesos Artísticos I, II, III y IV (YPA)",
  "Teoría Política 1 (TP1)",
  "Teoría de las Organizaciones (TDO)",
  "Teoría y Técnica Impositiva (TTI)",
  "Teorías de la Comunicación (TLC)",
  "Terapista Ocupacional (/TO)",
  "Termodinámica (TDN)",
  "Termodinámica y Máquinas Térmicas (TMT)",
  "Trabajo Corporal (YRC)",
  "Trabajo Social (T.S)",
  "Trabajo y Ciudadanía (TYC)",
  "Trayectorias Educativas de Jóvenes y Adultos (TJA)",
  "Turismo e Identidad, Turismo: Protocolo y Organización- Gastronomía-Desarrollo Socioeconómico (C5T)",
  "Turismo y Desarrollo Sustentable - Política y Legislación en Turismo (CA5)",
  "Técnicas de Diagnóstico (TED)",
  "Unión y Conformación de los Materiales (UYC)",
  "Uso y Desarrollo de Aplicaciones 1-2 (CUU)",
  "Verano C.E. Educación Física (CEF)",
  "Verano C.E. Maestros Especial (CEE)",
  "Vivero (VVR)",
  "Ética y Deontología Profesional (EDP)",
];

export const DISTRITO_KEYS = [
  "25 de mayo",
  "9 de julio",
  "adolfo alsina",
  "alberti",
  "almirante brown",
  "arrecifes",
  "avellaneda",
  "ayacucho",
  "azul",
  "bahia blanca",
  "balcarce",
  "baradero",
  "benito juarez",
  "berazategui",
  "berisso",
  "bolivar",
  "bragado",
  "brandsen",
  "campana",
  "capitan sarmiento",
  "carlos casares",
  "carlos tejedor",
  "carmen de areco",
  "castelli",
  "cañuelas",
  "chacabuco",
  "chascomus",
  "chivilcoy",
  "colon",
  "coronel dorrego",
  "coronel pringles",
  "coronel rosales",
  "coronel suarez",
  "daireaux",
  "dolores",
  "ensenada",
  "escobar",
  "esteban echeverria",
  "exaltacion de la cruz",
  "ezeiza",
  "florencio varela",
  "florentino ameghino",
  "general alvarado",
  "general alvear",
  "general arenales",
  "general belgrano",
  "general guido",
  "general la madrid",
  "general las heras",
  "general lavalle",
  "general madariaga",
  "general paz",
  "general pinto",
  "general pueyrredon",
  "general rodriguez",
  "general san martin",
  "general viamonte",
  "general villegas",
  "gonzales chaves",
  "guamini",
  "hipolito irigoyen",
  "hurlingham",
  "ituzaingo",
  "jose c. paz",
  "junin",
  "la matanza",
  "la plata",
  "lanus",
  "laprida",
  "las flores",
  "leandro n alem",
  "lezama",
  "lincoln",
  "loberia",
  "lobos",
  "lomas de zamora",
  "lujan",
  "magdalena",
  "maipu",
  "malvinas argentinas",
  "mar chiquita",
  "marcos paz",
  "mercedes",
  "merlo",
  "monte",
  "monte hermoso",
  "moreno",
  "moron",
  "navarro",
  "necochea",
  "olavarria",
  "partido de la costa",
  "patagones",
  "pehuajo",
  "pellegrini",
  "pergamino",
  "pila",
  "pilar",
  "pinamar",
  "presidente peron",
  "puan",
  "punta indio",
  "quilmes",
  "ramallo",
  "rauch",
  "rivadavia",
  "rojas",
  "roque perez",
  "saavedra",
  "saladillo",
  "salliquelo",
  "salto",
  "san andres de giles",
  "san antonio de areco",
  "san cayetano",
  "san fernando",
  "san isidro",
  "san miguel",
  "san nicolas",
  "san pedro",
  "san vicente",
  "suipacha",
  "tandil",
  "tapalque",
  "tigre",
  "tordillo",
  "tornquist",
  "trenque lauquen",
  "tres arroyos",
  "tres de febrero",
  "tres lomas",
  "vicente lopez",
  "villa gesell",
  "villarino",
  "zarate",
];

export const DISTRITO_LABELS = [
  "25 de Mayo",
  "9 de julio",
  "Adolfo Alsina",
  "Alberti",
  "Almirante Brown",
  "Arrecifes",
  "Avellaneda",
  "Ayacucho",
  "Azul",
  "Bahía Blanca",
  "Balcarce",
  "Baradero",
  "Benito Juarez",
  "Berazategui",
  "Berisso",
  "Bolivar",
  "Bragado",
  "Brandsen",
  "Campana",
  "Capitan Sarmiento",
  "Carlos Casares",
  "Carlos Tejedor",
  "Carmen de Areco",
  "Castelli",
  "Cañuelas",
  "Chacabuco",
  "Chascomús",
  "Chivilcoy",
  "Colón",
  "Coronel Dorrego",
  "Coronel Pringles",
  "Coronel Rosales",
  "Coronel Suarez",
  "Daireaux",
  "Dolores",
  "Ensenada",
  "Escobar",
  "Esteban Echeverría",
  "Exaltación de la Cruz",
  "Ezeiza",
  "Florencio Varela",
  "Florentino Ameghino",
  "General Alvarado",
  "General Alvear",
  "General Arenales",
  "General Belgrano",
  "General Guido",
  "General La Madrid",
  "General Las Heras",
  "General Lavalle",
  "General Madariaga",
  "General Paz",
  "General Pinto",
  "General Pueyrredón",
  "General Rodríguez",
  "General San Martín",
  "General Viamonte",
  "General Villegas",
  "Gonzales Chaves",
  "Guamini",
  "Hipolito Irigoyen",
  "Hurlingham",
  "Ituzaingo",
  "Jose C. Paz",
  "Junín",
  "La Matanza",
  "La Plata",
  "Lanús",
  "Laprida",
  "Las Flores",
  "Leandro N. Alem",
  "Lezama",
  "Lincoln",
  "Lobería",
  "Lobos",
  "Lomas de Zamora",
  "Luján",
  "Magdalena",
  "Maipú",
  "Malvinas Argentinas",
  "Mar Chiquita",
  "Marcos Paz",
  "Mercedes",
  "Merlo",
  "Monte",
  "Monte Hermoso",
  "Moreno",
  "Moron",
  "Navarro",
  "Necochea",
  "Olavarría",
  "Partido de la Costa",
  "Patagones",
  "Pehuajó",
  "Pellegrini",
  "Pergamino",
  "Pila",
  "Pilar",
  "Pinamar",
  "Presidente Perón",
  "Puan",
  "Punta Indio",
  "Quilmes",
  "Ramallo",
  "Rauch",
  "Rivadavia",
  "Rojas",
  "Roque Pérez",
  "Saavedra",
  "Saladillo",
  "Salliquelo",
  "Salto",
  "San Andres de Giles",
  "San Antonio de Areco",
  "San Cayetano",
  "San Fernando",
  "San Isidro",
  "San Miguel",
  "San Nicolás",
  "San Pedro",
  "San Vicente",
  "Suipacha",
  "Tandil",
  "Tapalque",
  "Tigre",
  "Tordillo",
  "Tornquist",
  "Trenque Lauquen",
  "Tres Arroyos",
  "Tres de Febrero",
  "Tres Lomas",
  "Vicente López",
  "Villa Gesell",
  "Villarino",
  "Zarate",
];

export const ESTADO_KEYS = [
  "anulada",
  //   "cerrada",
  "desierta",
  "designada",
  "finalizada",
  "publicada",
  "renunciada",
];

export const ESTADO_LABELS = [
  "Anulada",
  //   "Cerrada",
  "Desierta",
  "Designada",
  "Finalizada",
  "Publicada",
  "Renunciada",
];

export const MODALIDAD_KEYS = [
  "adultos y cens",
  "artistica",
  "educacion fisica",
  "especial",
  "inicial",
  "primaria",
  "psicologia",
  "secundaria",
  "secundaria adultos",
  "superior",
  "tecnico profesional",
];

export const MODALIDAD_LABELS = [
  "Adultos y CENS",
  "Artística",
  "Educación Física",
  "Especial",
  "Inicial",
  "Primaria",
  "Psicología",
  "Secundaria",
  "Secundaria Adultos",
  "Superior",
  "Técnico Profesional",
];
