export const CARGOS = [
  "derecho económico y del trabajo (cta)",
  "fines educación artística: danza (wdz)",
  "fines educación artística: música (wmc)",
  "fines educación artística: plástica (wpv)",
  "fines educación artística: teatro (wtt)",
  "fines educación física (wfc)",
  "4ta proyecto, diseño e instalaciones de energías renovables (pd4)",
  "5ta proyecto, diseño e instalaciones de energías renovables (pd5)",
  "abordaje de la interpretacion (ydi)",
  "actuacion (a.c)",
  "actuacion (ctu)",
  "actuación y procedimientos constructivos en teatro (poc)",
  "administracion (a.d)",
  "administracion de capacidades-gestion econimico comercial (cag) (cag)",
  "administración y gestión de los recursos humanos (arh)",
  "agroalimentos (aga)",
  "alimentos (a.l)",
  "ambiente, desarrollo y sociedad (ads)",
  "analisis del lenguaje teatral (yea)",
  "analisis y produccion en musica (yem)",
  "antropologia (a.n)",
  "antropologia y cultura (an2)",
  "análisis coreográfico (cor)",
  "análisis de modelos circuitales (moc)",
  "análisis de producción en música (pem)",
  "análisis del lenguaje teatral (tea)",
  "análisis matemático (am)",
  "aplicaciones de electrónica analógica (aea)",
  "aplicaciones de electrónica digital (aed)",
  "area administracion (/2a)",
  "area administracion cens - adultos (+2a)",
  "area ciencias biologicas cens - adultos (+3a)",
  "area ciencias de la educacion cens - adultos (+2o)",
  "area contabilidad cens - adultos (+2r)",
  "area cs.politicas y juridicas cens - adultos (+2u)",
  "area economia cens - adultos (+3g)",
  "area filosofia cens - adultos (+3p)",
  "area fisica cens - adultos (+5x)",
  "area historia cens - adultos (+3w)",
  "area informatica cens - adultos (+3z)",
  "area ingles cens - adultos (+4f)",
  "area ingles de la educacion general basica-egb (/ai)",
  "area lengua y literatura cens - adultos (+4b)",
  "area matematica cens - adultos (+4i)",
  "area medicina cens - adultos (+4o)",
  "area psicologia cens - adultos (+4s)",
  "area quimica cens - adultos (+5y)",
  "area sociologia cens - adultos (+4w)",
  "area tecnologia cens - adultos (+3d)",
  "areas de centro de produccion total (cpt)",
  "arte (leng. compl. de la danza): artes visuales (cd3)",
  "arte (leng. compl. de la danza): música (cd2)",
  "arte (leng. compl. de la danza): teatro (cd1)",
  "arte (leng. compl. de la lit.): artes visuales (cl2)",
  "arte (leng. compl. de la lit.): danza (cl3)",
  "arte (leng. compl. de la lit.): música (cl4)",
  "arte (leng. compl. de la literatura): teatro (cl1)",
  "arte (leng. compl. de la música): artes visuales (cm2)",
  "arte (leng. compl. de la música): danza (cm3)",
  "arte (leng. compl. de la música): teatro (cm1)",
  "arte (leng. compl. de las artes visuales): danza (ca3)",
  "arte (leng. compl. de las artes visuales): música (ca2)",
  "arte (leng. compl. de las artes visuales): teatro (ca1)",
  "arte (leng. compl. del teatro): danza (ct3)",
  "arte (leng. compl. del teatro): artes visuales (ct2)",
  "arte (leng. compl. del teatro): música (ct1)",
  "arte (rte)",
  "arte digital y diseño web (adw)",
  "asistente educacional (*ae)",
  "asistente social (*as)",
  "auditoria y control de gestión (aud)",
  "ayudante del area musica-practica de conjunto (a3b)",
  "bases de datos (bdd)",
  "bibliotecario (/be)",
  "bibliotecario (/bi)",
  "bibliotecario (/bp)",
  "bibliotecario (bla)",
  "bibliotecario de cens (/ba)",
  "bibliotecario de cie (bie)",
  "bibliotecario institutos terciarios artistica (bli)",
  "bibliotecario nivel inicial (/bj)",
  "biologia (b.g)",
  "biologia (blg)",
  "biologia y su enseñanza (b.p)",
  "biología y ambiente - biología y salud (c3a)",
  "biología, genética y sociedad (bgs)",
  "c.e.: administración de capacidades - gestión económico comercial (jag)",
  "c.e.: bases de datos y proyecto de software libre (jbp)",
  "c.e.: bibliotecario en contexto de encierro (jbi)",
  "c.e.: biología y ambiente/ biología y salud (j3a)",
  "c.e.: ciencias sociales 1 y 2 (jvw)",
  "c.e.: ciudadanía, sociedad y cultura - relaciones laborales y orientación profesional (j2u)",
  "c.e.: comunicación y cultura (jcc)",
  "c.e.: derecho ambiental y políticas ambientales (jda)",
  "c.e.: derecho económico y del trabajo (jet)",
  "c.e.: derechos humanos (jdh)",
  "c.e.: desarrollo sustentable 1 y 2 (jal)",
  "c.e.: economía y economía popular, social y solidaria (jee)",
  "c.e.: educación artística 1 y 2 plastica (jpv)",
  "c.e.: educación artística 1 y 2 teatro (jat)",
  "c.e.: educación física 1 y 2 (jfc)",
  "c.e.: filosofía (jff)",
  "c.e.: física: fenómenos naturales y procesos productivos (j5x)",
  "c.e.: gestión del diseño de emprendimientos/administración pública (j2a)",
  "c.e.: ingles (jin)",
  "c.e.: legislación y práctica impositiva - herramientas legales para emprendimientos (jlh)",
  "c.e.: lengua adicional ingles (j4f)",
  "c.e.: maestro bibliotecario (jmb)",
  "c.e.: maestro de ciclo (jcl)",
  "c.e.: matematica (jma)",
  "c.e.: matemática 1 y 2 (j4i)",
  "c.e.: metodología de la investigación (jmm)",
  "c.e.: preceptor (jpk)",
  "c.e.: primera disciplina/ lenguaje de la orientación 1 y 2 teatro (jlt)",
  "c.e.: probl. social contemporánea (jhp)",
  "c.e.: problemática social argentina (jpp)",
  "c.e.: proyecto de producción teatro -proyecto producción (jjt)",
  "c.e.: prácticas del lenguaje 1 y 2 (j4b)",
  "c.e.: quimica (jqu)",
  "c.e.: sistemas contables/gestión contable de emprendimientos (j2r)",
  "c.e.: sociología 1 y 2 (j4w)",
  "c.e.: tecnología y prácticas digitales 1 y 2 (j3z)",
  "canto coral (ycn)",
  "canto popular (ycr)",
  "capital humano y relaciones laborales (chr)",
  "centrales eléctricas (cen)",
  "cereales (cer)",
  "ciencias de la educacion (c.e)",
  "ciencias de la tierra (cdt)",
  "ciencias naturales (cnt)",
  "ciencias politicas (c.p)",
  "ciencias sociales (csc)",
  "ciencias sociales 1 -2 (cvw)",
  "ciudadania, sociedad y cultura-relaciones laborales y orientacion profesional (c2u) (c2u)",
  "cobertura de asignaturas formación profesional (fpg)",
  "combustión de los motores endotérmicos (moe)",
  "comunicacion social (c.s)",
  "comunicación y cultura 1-2 (ccc) (ccc)",
  "comunicación y culturas del consumo (cyc)",
  "comunicación y transf. socioculturales siglo xxi (cyt)",
  "comunicación, cultura y sociedad (ccs)",
  "conocimiento de los materiales (m. mayor de obras) (cmm)",
  "conocimiento de los materiales (téc. automotores) (cma)",
  "conocimiento de los materiales (téc. electromec.) (cme)",
  "construccion de ciudadania (ccd)",
  "controles y automatismo (4°, 5° y 6° año) (cya)",
  "coordinador institucional (coi)",
  "coordinador institucional de trayectorias educativas (cit)",
  "danza (adz)",
  "danza clasica i, ii, iii y iv (ycl)",
  "danza folklorica y popular i, ii, iii, iv y v (yfp)",
  "danzas expresion corporal (*7c)",
  "danzas tradicionales argentinas (*7b)",
  "deportes abiertos (d.a)",
  "derecho (der)",
  "derecho (drc)",
  "derecho administrativo (d.d)",
  "derecho ambiental y politicas ambientales (cdp) (cdp)",
  "derecho civil (d.c)",
  "derecho del trabajo y seguridad social (d.t)",
  "derecho penal (d.p)",
  "derechos del trabajo (det)",
  "derechos humano 1-2 (cdh) (cdh)",
  "derechos humanos y ciudadanía (dhu)",
  "desarrollo de aplicaciones web dinámicas (dwd)",
  "desarrollo de aplicaciones web estáticas (dwe)",
  "desarrollo regional (crd) (crd)",
  "desarrollo sustentable 1 - 2 (cal)",
  "destinos turisticos (tdt)",
  "dibujo tecnológico (maestro mayor de obras) (dtm)",
  "dibujo tecnológico (tecnico electromecanica) (dte)",
  "didactica de la biologia (dbi)",
  "didactica y curriculum (dyc)",
  "dificil cobertura (dca)",
  "dinamica de grupos (pc2)",
  "dirección de la ejecución de instalaciones (dej)",
  "director (xxd)",
  "director de escuela de verano (dev)",
  "diseño asistido y simulación electrónica (das)",
  "diseño de emprendimientos turisticos (cjf)",
  "diseño y gestion de proyectos turisticos sociocomunitarios (dgp)",
  "diseño y gestión de proyectos (dis)",
  "diseño y procesamiento mecánico (prm)",
  "docente coordinador/a de trayectorias - resol.1873/22 (ps6)",
  "docente integrador de circulos y trayectorias (d8d)",
  "documentación técnica (dot)",
  "economia y economia popular, social y solidaria (cec)",
  "economía (eno)",
  "economía política (epo)",
  "educacion (*4a)",
  "educacion fisica (e.f)",
  "educacion fisica (efc)",
  "educacion fisica y su enseñanza (e.d)",
  "educación artística 1 - 2: música (cmc)",
  "educación artística 1 -2 : danza (cdz)",
  "educación artística 1 -2: plástica (cpv)",
  "educación artística 1 -2: teatro (ctt)",
  "educación física 1- 2 (cfc)",
  "educación física y comunidad (efu)",
  "educación física y corporeidad (fco)",
  "educación física y cultura (efi)",
  "ejercico profesional de la construcción (epc)",
  "electrotecnia (nia)",
  "electrotecnia del automotor (eau)",
  "electrotecnia y electronica (t.e.i.e.) (-6k)",
  "electrónica (ect)",
  "electrónica aplicada (ela)",
  "electrónica industrial (ein)",
  "electrónica y autotrónica (nic)",
  "elementos de micro y macro economía (emm)",
  "ematp tecnología de la leche (etl)",
  "emprendimientos productivos y desarrollo local (edl)",
  "enc. de medios de apoyo tec-pedag. en c.sociales (ecs)",
  "enc.medios apoyo tecnico-pedag.especialidad taller (/pa)",
  "encarg. medios apoyo tec. pedag. area informatica (pli)",
  "encargado medios apoyo tec-ped. cs fisicas (eff)",
  "encargado medios apoyo tec-ped.biologia (ebb)",
  "encargado medios apoyo tec-ped.comunic. arte y dis (ead)",
  "encargado medios apoyo tec-ped.construc.civiles (eco)",
  "encargado medios apoyo tec-ped.econ.y ges.organiza (elc)",
  "encargado medios apoyo tec-ped.electronica (eel)",
  "encargado medios apoyo tec-ped.inf/comp/e inf.apl. (eli)",
  "encargado medios apoyo tec-ped.med/equip/ins.elec. (eld)",
  "encargado medios apoyo tec-ped.quimica (eqq)",
  "encargadomedios apoyo tec-ped.biologia (ebb)",
  "escenoplastica (ysc)",
  "escuela de verano contexto de encierro (cev)",
  "escuela de verano educación física (vef)",
  "escuela de verano guardavida (vgu)",
  "espacio complementario ( escultura ) (yce)",
  "espacio complementario ( grabado) (ycg)",
  "espacio de la especialidad (grabado ) (yeg)",
  "espacio de la especialidad (pintura ) (ypi)",
  "espacio de profundizacion del aprendizaje (epa)",
  "espacios turísticos de la argentina (eta)",
  "estructuras (esr)",
  "estudios interculturales en inglés (est)",
  "filosofia (*6a)",
  "filosofia (f.i)",
  "filosofia (fia)",
  "filosofia 1-2 (cff) (cff)",
  "filosofía (fia)",
  "filosofía e historia de la ciencia y la tecnología (fct)",
  "fines administración pública, de capacidades y relaciones laborales 2do año (waa)",
  "fines biología (wcb)",
  "fines ciudadanía, sociedad, cultura y relaciones laborales 2do año (wcr)",
  "fines comunicación y cultura 3er año (wcc)",
  "fines comunicación y medios (wcm)",
  "fines contabilidad (wco)",
  "fines derecho (wdd)",
  "fines derechos humanos 2do año (wdh)",
  "fines educación artística: literatura y escritura (wle)",
  "fines educación artística: música (wmc)",
  "fines educación artística: plástica (wpv)",
  "fines educación física (wfc)",
  "fines filosofía 3er año (wfp)",
  "fines fisica (wff)",
  "fines fundamentos de economía y perspectiva popular, social y solidaria 3er año (weg)",
  "fines historia y geografia (whg)",
  "fines informática (wif)",
  "fines ingles (win)",
  "fines legislación impositiva y herramientas para emprendimientos 3er año (wru)",
  "fines lengua y literatura (wll)",
  "fines matemática (wmt)",
  "fines metodología de la investigación (wmi)",
  "fines planificacion y gestion de emprendimientos (esp.2º) (wpg)",
  "fines practica contable laboral e impositiva (esp.3º) (wpc)",
  "fines problemática social argentina 3er año (wsp)",
  "fines problemática social contemporanea (wps)",
  "fines psicología (wpa)",
  "fines quimica (wqq)",
  "fines sociología (wss)",
  "fisica y su enseñanza (f.t)",
  "fisica: fenomenos naturales y procesos productivos (c5x) (c5x)",
  "fisico - quimica (fqa)",
  "fonoaudiologia (f.n)",
  "fonoaudiologo (/fo)",
  "forrajes (frj)",
  "fortalecimiento de trayectorias educativas (inicial) (mif)",
  "fortalecimiento de trayectorias educativas (primaria) (mgf) [prog. res. 417/21- 3206/21- 446/22 ] (mgf)",
  "fotografia (yot)",
  "francés (fra)",
  "fundamentos de la química (fdq)",
  "fundamentos de los modelos circuitales (fmc)",
  "fundamentos y modelos de mecanica clasica (fmm)",
  "física (fis)",
  "física clásica y moderna (fcm)",
  "ganaderia (gnd)",
  "ganaderia de carne (gca)",
  "ganadería de leche (gdl)",
  "genetica y evolucion (g.e)",
  "geografia (ggf)",
  "geografia de genero (gge)",
  "gestión comercial (gco)",
  "gestión de la producción (ges)",
  "gestión de proyectos (gdp)",
  "gestión de proyectos (gpr)",
  "gestión del diseño de emprendimientos - administración pública (c2a)",
  "gestión financiera bancaria y seguros (fin)",
  "gestión organizacional (gor)",
  "granja 1º y 2º año (gra)",
  "gráfica editorial (gre)",
  "guardavidas (gu)",
  "guión (5° año) (gui)",
  "historia (h.i)",
  "historia (htr)",
  "historia contemporanea (h.c)",
  "huerta (hue)",
  "imagen y nuevos medios (inm)",
  "imagen y nuevos medios (ynm)",
  "imagen y procedimientos constructivos (lep)",
  "imagen y procedimientos constructivos (yip)",
  "improvisación y composición coreográfica (imp)",
  "informatica (i.f)",
  "ingles (i.n)",
  "ingles (igs)",
  "inglés específico (ing)",
  "iniciacion a la danza folklorica y popular (ydf)",
  "instalaciones eléctricas (ie)",
  "instalaciones industriales (iim)",
  "instalaciones industriales (ind)",
  "instalaciones sanitarias y de gas (isi)",
  "instalaciones y aplicaciones de la energía (ape)",
  "instalaciones y maquinas eléctricas (imo)",
  "instalación, mantenimiento y reparación de redes informáticas (iri)",
  "instalación, mantenimiento y reparación de sistemas computacionales (imc)",
  "instructor/a de formación profesional - resol.1873/22 (ps5)",
  "instrumental de medición (imu)",
  "instrumento (yns)",
  "instrumento (piano o guitarra) (yii)",
  "instrumento complementario (ync)",
  "instrumento principal (ynp)",
  "intensificación agropecuaria (ia)",
  "interpretación de anteproyectos (ian)",
  "introduccion a los multimedios (iam)",
  "introduccion al portugues (ipo)",
  "introducción a la biología celular (ibc)",
  "introducción a la comunicación (iac)",
  "introducción a la electricidad y mediciones (iem)",
  "introducción a la física (iaf)",
  "introducción a la programación orientada a objetos (ioo)",
  "introducción a la química (iaq)",
  "introducción a las organizaciones (ior)",
  "introducción al turismo - prestadores turísticos (c5a)",
  "introducción al turismo y oferta turística (itt)",
  "investigación del medio 1° y 2° año (ime)",
  "investigación operativa (ope)",
  "italiano (ita)",
  "jornada escolar de 25 horas- maestro de apoyo - [prog. res. 2502/22] (ma5)",
  "jornada escolar de 25 horas- maestro de grado - [prog. res. 2502/22] (mg5)",
  "kinesiologo (/ki)",
  "lab. de op. unit. y tecnología de los materiales (lot)",
  "laboratorio de análisis microbiológicos (lam)",
  "laboratorio de aplicaciones (lap)",
  "laboratorio de diseño de bases de datos (ldb)",
  "laboratorio de diseño web (ldw)",
  "laboratorio de ensayo de motores (ens)",
  "laboratorio de ensayos físicos (lef)",
  "laboratorio de ensayos industriaes (lei)",
  "laboratorio de hardware (lhw)",
  "laboratorio de mediciones electricas (lme)",
  "laboratorio de metrología y control de calidad (lcc)",
  "laboratorio de procesos industriales (lpi)",
  "laboratorio de procesos industriales (pri)",
  "laboratorio de programación (lpr)",
  "laboratorio de quimica organica biologica y micro (qui)",
  "laboratorio de química (lqi)",
  "laboratorio de química orgánica (qor)",
  "laboratorio de química orgánica, biológica y microbiológica (alimentos) (qua)",
  "laboratorio de sistemas operativos (lso)",
  "laboratorio de técnicas analíticas (tec)",
  "legislacion y practica monetaria-herramientas legales para emprendimientos (clh) (clh)",
  "lengua (l.n)",
  "lengua adicional 1 - 2: inglés (c4f)",
  "lengua y su enseñanza (l.p)",
  "lenguaje complementario (artes visuales) (yca)",
  "lenguaje complementario (danza) (ylz)",
  "lenguaje complementario (musica) (ycm)",
  "lenguaje complementario (teatro) (ylt)",
  "lenguaje de la danza (led)",
  "lenguaje musical (yen)",
  "lenguaje musical (len)",
  "lenguaje visual i y ii (yvl)",
  "lenguajes artísticos/ música (ltm)",
  "lenguajes artísticos/ plástica (ltp)",
  "lenguajes artísticos/ teatro y diseño escenográfico (ltt)",
  "lenguajes electrónicos (lee)",
  "lenguajes musicales contemporaneos (ymc)",
  "lenguajes tecnológicos (lt1)",
  "lenguajes tecnológicos (lt2)",
  "lenguajes tecnológicos (lte)",
  "lenguajes tecnológicos (lts)",
  "linguistica (l.g)",
  "literatura (l.t)",
  "literatura (lit)",
  "logistica (l.o)",
  "líneas de transmisión (ltr)",
  "ma-agricultura (agr)",
  "ma-avicultura (avi)",
  "ma-bovinos de carne (boc)",
  "ma-bovinos de leche (bol)",
  "ma-cunicultura (cun)",
  "ma-huerta (hor)",
  "ma-mecánica agrícola (meg)",
  "ma-máquinas, equipos, herramientas e inst. rurales (mir)",
  "ma-ovinos (ovi)",
  "ma-planta de elaboración de forrajes (efo)",
  "ma-porcinos (pos)",
  "ma-sala de elaboración de productos cárnicos (eca)",
  "ma-sala de elaboración de productos lácteos (epl)",
  "ma-sala de frutas y hortlizas (sfh)",
  "ma-taller rural (trm)",
  "ma-vivero (pvi)",
  "maest.auxiliar taller armado (*ra)",
  "maest.auxiliar taller carpinteria (*ca)",
  "maest.auxiliar taller confeccion (*cf)",
  "maest.auxiliar taller construcciones (*cn)",
  "maest.auxiliar taller mecanica (*tm)",
  "maest.auxiliar taller servicios (*ts)",
  "maestra bibliotecaria rama adultos (/mb)",
  "maestra de infantes (/mi)",
  "maestra de jardin maternal (/jm)",
  "maestra de pre-taller de costura (/tc)",
  "maestra hospitalaria (/dh)",
  "maestra iniciacion literaria escuelas de estetica (mil)",
  "maestro alteraciones en el desarrollo del lenguaje (/al)",
  "maestro ciegos y disminuidos visuales (/dc)",
  "maestro de apoyo (ma)",
  "maestro de apoyo para escuelas laborales (/ab)",
  "maestro de armado (/ra)",
  "maestro de articulacion (/ar)",
  "maestro de ciclo (/mc)",
  "maestro de danza primaria (mdp)",
  "maestro de danza primaria de especial (mde)",
  "maestro de discapacitados motores (/dm)",
  "maestro de educacion visual inicial (mvi)",
  "maestro de expresión corporal inicial (mei)",
  "maestro de expresión manual primaria (mmp)",
  "maestro de expresión plástica primaria (mpp)",
  "maestro de expresión plástica primaria de adultos (mpa)",
  "maestro de expresión plástica primaria de especial (mpe)",
  "maestro de grado (/mg)",
  "maestro de huerta y granja (/hg)",
  "maestro de iniciacion musical-escuelas de estetica (mim)",
  "maestro de irregulares mentales (/im)",
  "maestro de musica 2 hs cat (2ui)",
  "maestro de musica-apoyo rama inicial (mui)",
  "maestro de música 3 hs cat (3ui)",
  "maestro de música primaria (mup)",
  "maestro de música primaria de adultos (mua)",
  "maestro de música primaria de especial (mue)",
  "maestro de orientacion manual (/om)",
  "maestro de pre-taller de jardineria (/jd)",
  "maestro de pre-taller de mantenimiento i (/tu)",
  "maestro de pre-taller de mantenimiento ii (/ms)",
  "maestro de sordos e hipoacusicos (/sh)",
  "maestro de taller (/ta)",
  "maestro de taller de carpinteria (/ca)",
  "maestro de taller de confeccion (/cf)",
  "maestro de taller de construcciones (/cn)",
  "maestro de taller de integracion laboral (/la)",
  "maestro de taller de marroquineria (/mq)",
  "maestro de taller de mecanica (/tm)",
  "maestro de taller de peluqueria (/pl)",
  "maestro de taller de servicios (/ts)",
  "maestro de taller de tejido (/tj)",
  "maestro de teatro inicial (mti)",
  "maestro de teatro primaria (mtp)",
  "maestro de teatro primaria de especial (mte)",
  "maestro domiciliario (/td)",
  "maestro educ.fisica apoyo rama especial. (/ze)",
  "maestro educ.fisica para 1º y 2º ciclo egb (/zp)",
  "maestro educación visual 2 hs cat (2vi)",
  "maestro educación visual 3 hs cat (3vi)",
  "maestro esp. intérprete pedag. lengua señas arg (lsa)",
  "maestro especial (/me)",
  "maestro especializado en grupos: inicial (/gi)",
  "maestro especializado en grupos: primario (/gp)",
  "maestro estimulador (/et)",
  "maestro expresion corporal escuelas educ.estetica (mec)",
  "maestro expresion dramatica escuelas educ.estetica (med)",
  "maestro expresion plastica bi-dimensional (mpb)",
  "maestro expresion plastica tri-dimensional (mpt)",
  "maestro expresión corporal 2 hs cat (2ei)",
  "maestro expresión corporal 3 hs cat (3ei)",
  "maestro intensificador [prog. res. 2275/22] (mai)",
  "maestro pretaller economia domest.y cuidados pers. (/ed)",
  "maestro recuperador (/mr)",
  "maestro seccion (/ma)",
  "maestro severos trastornos de la personalidad (/tp)",
  "maestro teatro 2 hs cat (2ti)",
  "maestro/a de formación general (/fg)",
  "mandos y automatismos (mya)",
  "manifestaciones culturales (mnc)",
  "mantenimiento de instalaciones (min)",
  "mantenimiento eléctrico (mae)",
  "mantenimiento y montaje electromecánico (mme)",
  "maquinarias agricolas/instalaciones rurales (mar)",
  "maquinas eléctricas y automatismos (mea)",
  "marketing de servicios (mks)",
  "matematica (mtm)",
  "matemática - ciclo superior (mcs)",
  "matemática 1 - 2 (c4i)",
  "matemática aplicada (map)",
  "matemática discreta (mdi)",
  "materiales de obra (mao)",
  "mecánica (mca)",
  "mecánica agrícola (gri)",
  "mecánica y mecanismos (mos)",
  "medicina (m.d)",
  "mediciones equip. e instalaciones electromecanicas (ele)",
  "medico clinico - medico pediatra (/dd)",
  "medico especialista en rehabilitacion (/si)",
  "medico orientador (/do)",
  "metodologia de la investigacion (cms)",
  "metodologia de la investigacion (cna)",
  "metodologia de la investigacion (so1)",
  "microbiología de los alimentos (mic)",
  "modelos y sistemas (mys)",
  "montaje de proyectos electrónicos (mel)",
  "morfologia sonora (mfs)",
  "morfologia visual (mov)",
  "motores de combustión interna (mci)",
  "musica (amc)",
  "musica-apreciacion (*3c)",
  "musica-educacion musical (*9c)",
  "musica-elementos tecnicos (*3f)",
  "musica-elementos tecnicos (*9e)",
  "musica-guitarra (*3s)",
  "musica-iniciacion (*3a)",
  "musica-practica de conjunto (*3b)",
  "musica-violin (*8e)",
  "musica-violin (*8r)",
  "musicoterapeuta (/7d)",
  "máquinas eléctricas (maq)",
  "máquinas eléctricas y aplicaciones (mqe)",
  "máquinas y eementos para maniobra, elevación y transporte (mmt)",
  "máquinas y equipos (mye)",
  "mécanica agrícola (mag)",
  "neuropsicopatologia (pq1)",
  "nticx (nti)",
  "nutricion: vidas saludables y etapas de la vida (cnn) (cnn)",
  "observatorio de comunicación cultura y sociedad (ocs)",
  "observatorio de medios (odm)",
  "oleaginosas y cultivos industriales (oci)",
  "op-administración agraria (ada)",
  "op-producción de agroalimentos (pag)",
  "op-producción de carnes (pdc)",
  "op-producción de cereales, oleaginosas y cultivos industriales (pco)",
  "operaciones uni. y tecnología de los materiales (out)",
  "operaciones unitarias y representación gráfica (oug)",
  "operadores y sistemas mecánicos (ops)",
  "organizacion y gestion de la produccion agrop. (oga)",
  "organización de la producción agropecuaria (apo)",
  "organización industrial y servicios (ois)",
  "organización y gestión del trabajo y la producción (gtp)",
  "organización y gestión industrial (ogi)",
  "organización y métodos (oym)",
  "orientador educacional (/oe)",
  "orientador educacional (secundaria) (soe)",
  "orientador social (/os)",
  "orientador social (secundaria) (sos)",
  "ot-administración agraria (adt)",
  "ot-producción de agroalimentos (pat)",
  "ot-producción de carne (pnt)",
  "ot-producción frutícola y forestal (ptt)",
  "panorama de la produccion contemporanea en danza (ycd)",
  "panorama de la produccion musical contemporanea (ypp)",
  "panorama de la produccion musical popular argentina y latino americana (ypm)",
  "patrimonio turístico nacional e internacional (ptu)",
  "pedagogico didactica (ce1)",
  "planeamiento (pla)",
  "planeamiento y evaluación de proyectos (pep)",
  "planificación de obra (pob)",
  "plastica (p.b)",
  "plastica - visual (apv)",
  "plastica-administracion cultural (*1p)",
  "plastica-comunicacion (*1k)",
  "plastica-dibujo (*1f)",
  "plastica-grafica (*1h)",
  "plastica-historia (*1j)",
  "plastica-pintura (*1a)",
  "politicas publicas y promocion comunicativa 1-2 (c2p) (c2p)",
  "política y ciudadanía (pyc)",
  "portugues (p.g)",
  "portugués (por)",
  "pp-producción de agroalimentos (p05)",
  "pp-producción de carnes (p01)",
  "pp-producción de leche (p02)",
  "practica de conjuntos vocales e instrumentales (yci)",
  "practica docente egb (p.d)",
  "practica docente ii (taller) (pd2)",
  "practicas del lenguaje (plg)",
  "practicas turisticas (tpt)",
  "preceptor (/pr)",
  "preceptor (pr)",
  "preceptor (pra)",
  "preceptor de institutos terciarios artistica (prt)",
  "preceptor de jardin maternal (/pm)",
  "preceptor escuelas de estetica (pee)",
  "primera disciplina / lenguaje de la orientación 1 -2: teatro (cat)",
  "problemas socioambientales - soberanía alimentaria y derecho a la alimentación (cww)",
  "problematicas del desarrollo latinoamericano (plt)",
  "problemática social artentina 1-2 (cpp) (cpp)",
  "procedimientos técnicos (pce)",
  "procedimientos técnicos (pcs)",
  "procedimientos técnicos (pct)",
  "procedimientos técnicos (pt1)",
  "procedimientos técnicos (pt2)",
  "procesamiento mecánico (pmo)",
  "procesos químicos y control (pqc)",
  "produc. y analisis de la imagen (yai)",
  "produccion musical grupal i, ii y iii (ymg)",
  "producción y análisis de la imagen (pai)",
  "producción y comercio exterior (pre)",
  "producción y utilización de forrajes (puf)",
  "prof. de c.e.f. (/ef)",
  "prof.educ.fisica apoyo rama adultos (/za)",
  "profesor de teatro 3° ciclo egb especial (pts)",
  "profesor educ.fisica apoyo a rama inicial. (/zi)",
  "profesor educ.fisica apoyo a rama psicologia (/zs)",
  "profesor educacion fisica apoyo rama inicial 2 hs (2zi)",
  "profesor/a de ciencias naturales -resol.1873/22 (ps3)",
  "profesor/a de ciencias sociales - resol.1873/22 (ps4)",
  "profesor/a de inglés res. 1873/22 (ps7)",
  "profesor/a de matemática -resol.1873/22 (ps1)",
  "profesor/a de prácticas del lenguaje - resol.1873/22 (ps2)",
  "programacion de objetos y taller de multimedia (cpr)",
  "programación de circuitos (prc)",
  "proyecto (orp)",
  "proyecto 7mo tecnica (p7t)",
  "proyecto de implementación de sitios web dinámicos (pwd)",
  "proyecto de produccion (ydp)",
  "proyecto de produccion en artes visuales (yav)",
  "proyecto de producción en artes visuales (pav)",
  "proyecto de producción en danza (ppd)",
  "proyecto de producción en literatura (ppl)",
  "proyecto de producción en música (ppm)",
  "proyecto de producción en teatro (ppt)",
  "proyecto final (prf)",
  "proyecto tecnica (pt0)",
  "proyecto y diseño electromecánico (pdn)",
  "proyecto y diseño electrónico (pye)",
  "proyecto, diseño e instalaciones de energías renovables (pd6)",
  "proyectos de artistica (par)",
  "proyectos de educacion agraria (pea)",
  "proyectos de instalaciones (pin)",
  "proyectos de investigación en ciencias sociales (pic)",
  "proyectos de superior (psu)",
  "proyectos organizacionales (pro)",
  "prácticas corporales y dep en el ambiente natural (pcd)",
  "prácticas de conjuntos vocales e instrumentales (pci)",
  "prácticas del lenguaje 1 - 2 (c4b)",
  "prácticas deportivas y acuáticas (pdo)",
  "prácticas deportivas y atléticas (pdi)",
  "prácticas deportivas y juegos (pdj)",
  "prácticas gimnásticas y expresivas (pge)",
  "psicologia (p.s)",
  "psicologia social (p.c)",
  "psicologia social del turismo (sst)",
  "psicologia social e institucional (pc1)",
  "psicologo (/po)",
  "psicología (psi)",
  "psicología del desarrollo - psicología social e institucional (c4s)",
  "psicopedagogia (p.p)",
  "quimica (qmc)",
  "quimica y su enseñanza (q.e)",
  "quimica: tecnoligia y sociedad (cqq) (cqq)",
  "química analítica (qan)",
  "química del carbono (qdc)",
  "química general e inorgánica (qgi)",
  "química industrial (qi)",
  "química orgánica (qo)",
  "química orgánica biológica (qob)",
  "química orgánica y biológica (alim) (qoa)",
  "realización audiovisual (7° año) (rau)",
  "rectificación de motores (rmo)",
  "recursos lingüísticos (rli)",
  "relaciones públicas protocolo y ceremonial (rpp)",
  "relevamiento ambiental (rea)",
  "resistencia y ensayos de los materiales (rem)",
  "salud (s.a)",
  "salud y adolescencia (sya)",
  "salud y cultura 1 - 2 (cao)",
  "salud: genero y trabajo (css) (css)",
  "seguridad e higiene (s.h)",
  "seguridad informática (ins)",
  "seminario de accesibilidad turistica (sat)",
  "seminario de investigación literaria (sil)",
  "seminario turismo y sustentabilidad (sty)",
  "servicios turísticos (stu)",
  "sistema electroenergético (sle)",
  "sistemas autotrónicos (sa)",
  "sistemas constructivos i - ii (sct)",
  "sistemas constructivos (sco)",
  "sistemas contables - gestión contable de emprendimientos (c2r)",
  "sistemas de comunicaciones (sc)",
  "sistemas de gestión y autogestión (sga)",
  "sistemas de información contable (sic)",
  "sistemas de inyección (si)",
  "sistemas de transmisión (str)",
  "sistemas digitales (sd)",
  "sistemas hidráulicos y neumáticos (shn)",
  "sistemas mecánicos (sm)",
  "sistemas multimediales (6° año) (sim)",
  "sistemas productivos (sp)",
  "sistemas tecnológicos (st1)",
  "sistemas tecnológicos (st2)",
  "sistemas tecnológicos (st3)",
  "sistemas tecnológicos (st4)",
  "sistemas tecnológicos (sts)",
  "sociologia (s.o)",
  "sociologia 1-2 (c4w) (c4w)",
  "sociologia y procesos organizacionales en salud 1-2 (csp) (csp)",
  "sociología (soc)",
  "sociología 1 - 2 (caw)",
  "síntesis de imagen y animación (sia)",
  "taller de composicion (ydc)",
  "taller de comunicación institucional y comunitaria (tci)",
  "taller de escritura (tde)",
  "taller de literatura y escritura (tle)",
  "taller de percusion (ytn)",
  "taller de prod. tridimen. (yty)",
  "taller de produc. en dibujo e ilustracion (yti)",
  "taller de produc. en grabado y arte impreso (yga)",
  "taller de produc. en pintura (ytp)",
  "taller de produc. escultura y ceramica o arte del fuego (yar)",
  "taller de produccion literaria (ypl)",
  "taller de producción en lenguajes (ocl)",
  "taller rural (tru)",
  "teatro (*2a)",
  "teatro (*2b)",
  "teatro (att)",
  "teatro (yte)",
  "tecnico docente medico (tdm)",
  "tecnolog. electrónicas (téc.informát.prof.y pers.) (tee)",
  "tecnología de la información turística (tit)",
  "tecnología de las energías renovables (4°, 5° y 6° año) (ter)",
  "tecnología electrónica (técnico en electrónica) (tel)",
  "tecnología mecánica (tem)",
  "tecnología y producción gráfica (tpg)",
  "tecnología y prácticas digitales 1- 2 (c3z)",
  "tecnologías de la información de la gestión (tig)",
  "teleinformática (tli)",
  "teoria del turismo (ttt)",
  "teoria e historia de los procesos artisticos i, ii, iii y iv (ypa)",
  "teoria politica 1 (tp1)",
  "teoría de las organizaciones (tdo)",
  "teoría y técnica impositiva (tti)",
  "teorías de la comunicación (tlc)",
  "terapista ocupacional (/to)",
  "termodinámica (tdn)",
  "termodinámica y máquinas térmicas (tmt)",
  "trabajo corporal (yrc)",
  "trabajo social (t.s)",
  "trabajo y ciudadanía (tyc)",
  "trayectorias educativas de jovenes y adultos (tja)",
  "turismo e identidad, turrismo: protocolo y organización- gastronomia-desarrollo socioeconomico (c5t) (c5t)",
  "turismo y desarrollo sustentable - política y legislación en turismo (ca5)",
  "unión y conformación de os materiales (uyc)",
  "uso y desarrollo de aplicaciones 1-2 (cuu) (cuu)",
  "verano c.e. educacion fisica (cef)",
  "verano c.e. maestros especial (cee)",
  "vivero (vvr)",
  "ética y deontología profesional (edp)",
];

export const DISTRITOS = [
  "25 de mayo",
  "9 de julio",
  "adolfo alsina",
  "alberti",
  "almirante brown",
  "arrecifes",
  "avellaneda",
  "ayacucho",
  "azul",
  "bahia blanca",
  "balcarce",
  "baradero",
  "benito juarez",
  "berazategui",
  "berisso",
  "bolivar",
  "bragado",
  "brandsen",
  "campana",
  "capitan sarmiento",
  "carlos casares",
  "carlos tejedor",
  "carmen de areco",
  "castelli",
  "cañuelas",
  "chacabuco",
  "chascomus",
  "chivilcoy",
  "colon",
  "coronel dorrego",
  "coronel pringles",
  "coronel rosales",
  "coronel suarez",
  "daireaux",
  "dolores",
  "ensenada",
  "escobar",
  "esteban echeverria",
  "exaltacion de la cruz",
  "ezeiza",
  "florencio varela",
  "florentino ameghino",
  "general alvarado",
  "general alvear",
  "general arenales",
  "general belgrano",
  "general guido",
  "general la madrid",
  "general las heras",
  "general lavalle",
  "general madariaga",
  "general paz",
  "general pinto",
  "general pueyrredon",
  "general rodriguez",
  "general san martin",
  "general viamonte",
  "general villegas",
  "gonzales chaves",
  "guamini",
  "hipolito irigoyen",
  "hurlingham",
  "ituzaingo",
  "jose c. paz",
  "junin",
  "la matanza",
  "la plata",
  "lanus",
  "laprida",
  "las flores",
  "leandro n alem",
  "lezama",
  "lincoln",
  "loberia",
  "lobos",
  "lomas de zamora",
  "lujan",
  "magdalena",
  "maipu",
  "malvinas argentinas",
  "mar chiquita",
  "marcos paz",
  "mercedes",
  "merlo",
  "monte",
  "monte hermoso",
  "moreno",
  "moron",
  "navarro",
  "necochea",
  "olavarria",
  "partido de la costa",
  "patagones",
  "pehuajo",
  "pellegrini",
  "pergamino",
  "pila",
  "pilar",
  "pinamar",
  "presidente peron",
  "puan",
  "punta indio",
  "quilmes",
  "ramallo",
  "rauch",
  "rivadavia",
  "rojas",
  "roque perez",
  "saavedra",
  "saladillo",
  "salliquelo",
  "salto",
  "san andres de giles",
  "san antonio de areco",
  "san cayetano",
  "san fernando",
  "san isidro",
  "san miguel",
  "san nicolas",
  "san pedro",
  "san vicente",
  "suipacha",
  "tandil",
  "tapalque",
  "tigre",
  "tordillo",
  "tornquist",
  "trenque lauquen",
  "tres arroyos",
  "tres de febrero",
  "tres lomas",
  "vicente lopez",
  "villa gesell",
  "villarino",
  "zarate",
];

export const ESTADOS = [
  "anulada",
  "cerrada",
  "desierta",
  "designada",
  "finalizada",
  "publicada",
  "renunciada",
];

export const MODALIDADES = [
  "adultos y cens",
  "artistica",
  "educacion fisica",
  "especial",
  "inicial",
  "primaria",
  "psicologia",
  "secundaria",
  "secundaria adultos",
  "superior",
  "tecnico profesional",
];
